### ISSUE TITLE
Hidden Paging on ODH Calls

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/it.bz.opendatahub.databrowser#116]
Hi all

For easier integration on the Databrowser i added a hidden paging on several ODH Endpoints. 
The Paging is used when the parameter pagenumber=1 is passed, then the result data is wrapped into a Result object under the Items List. I had to be careful because of not breaking the current api responses,

example
`https://api.tourism.testingmachine.eu/v1/Region` vs
`https://api.tourism.testingmachine.eu/v1/Region?pagenumber=1`

On this endpoint now there is paging available
`https://api.tourism.testingmachine.eu/v1/MetaRegion?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/Region?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/ExperienceArea?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/TourismAssociation?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/Municipality?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/District?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/SkiArea?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/SkiRegion?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/WineAward?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/Weather?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/WeatherHistory?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/Weather/District?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/Weather/Measuringpoint?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/Weather/SnowReport?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/ODHTag?pagenumber=1`
`https://api.tourism.testingmachine.eu/v1/Tag?pagenumber=1`

@gappc  what do you think?

**Comment by gappc** [comment]
Hi @RudiThoeni, interesting solution, thank you

For the list-result case, (like https://api.tourism.testingmachine.eu/v1/Region), the Databrowser already detects if the result is pageable or a simple list: https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/ffa833cfbe00927e63425e79b833df3629bb37ec/databrowser/src/domain/api/client/mapper.ts#L62

Are there other cases where this could be relevant?

**Comment by RudiThoeni** [comment]
Hi @gappc the customer care which was configuring the databrowser told me that it did not work when the data was not returned inside the standard object

```javascript
TotalResults: 99,
TotalPages: 9,
CurrentPage: 1,
Items: []
{
```

so i added it to all calls, when you pass pagenumber it is wrapped inside. I find this not a bad practice, so the api remains in the same style.......

I had also the request from them for missing "Detail" methods so i added also this 
at example for
`
https://tourism.api.opendatahub.bz.it/v1/Weather/{id} --> https://tourism.api.opendatahub.bz.it/v1/Weather/77551
https://tourism.api.opendatahub.bz.it/v1/WeatherHistory/{id} --> https://tourism.api.opendatahub.bz.it/v1/WeatherHistory/25764
https://api.tourism.testingmachine.eu/v1/Weather/Realtime/{id} --> https://api.tourism.testingmachine.eu/v1/Weather/Realtime/800
https://api.tourism.testingmachine.eu/v1/Weather/SnowReport/{id} --> https://api.tourism.testingmachine.eu/v1/Weather/SnowReport/SKIFFC3B47C3CEA4426AE850E333EFE79CE_SNOWREPORT
`

**Comment by gappc** [comment]
@RudiThoeni could you please ask the customer care if there are still problems and if so for which endpoints? When I have that information I can take a look at possible problems.

**Comment by RudiThoeni** [comment]
customer care can always contact me, i am closing this issue now
