### ISSUE TITLE
As a Open Data Hub PM I want that all Table View configuration are configured in order to provide a better experience to the Data Browser users.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#129]
deadline: 31st August 2022

**Comment by sseppi** [comment]
In order to close this issue are missing:
- [ ] the configuration of the weather real time ( @lukmay is waiting for the documentation of the fields names)

**Comment by lukmay** [comment]
I received this information and opened a pull request: https://github.com/noi-techpark/it.bz.opendatahub.databrowser/pull/176#issue-1425141928
