### ISSUE TITLE
Build broke due to PR #131 merge

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#134]
@BlueRyse, @lukmay: unfortunately the merge of PR #131 broke the build (see https://github.com/noi-techpark/it.bz.opendatahub.databrowser/runs/8232015443?check_suite_focus=true).
The issue seems to be that number / boolean is not assignable to the `href` of the link element.

It would be nice if you could provide a fix: just remove the types `boolean | number` from the UrlCell component (see here: https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/3ab9439d3432172ae89d2e8cca7de93430a2124e/databrowser/src/domain/cellComponents/components/cells/UrlCell/UrlCell.vue#L14)

**Comment by BlueRyse** [comment]
I opened a PR that fixes this.

**Comment by gappc** [comment]
Hey @BlueRyse, the fix works, the component and configs are now online.

Thank you for your fast response 👍
