### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#138]
For example vue, vite, ...

**Comment by sseppi** [comment]
@gappc is still valid this issue? Shall we put in ToDo?

**Comment by gappc** [comment]
@sseppi yes this is still a valid issue, we should add it to the project planning

**Comment by sseppi** [comment]
@gappc ok, I added the issue at the ToDo line and we can discuss it at the next Sprint Meeting.

**Comment by gappc** [comment]
@sseppi all depenencies are updated
