### ISSUE TITLE
Component to render GPS coordinates on a Map

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#142]
As a data browser developer I want a map component to be used to show GPS coordinates on a map.

The web component should render:
- [x] render one or more GPS point accordingly to the number of points that is passed to the web component;
- [x] render one or more GPS tracks (e.g. lifts, bike tour, ski slopes, etc.) accordingly to the number of points that is passed to the web component (dedicated issue has been created: #361 );

Once the Web Component is developed We should remember to properly configure it in all Detail Views

**Comment by sseppi** [comment]
@BlueRyse and @d3liaa do you have news about this component?

**Comment by gappc** [comment]
@sseppi map visualization implemented by @MatteoBiasi in QuickView feature and reused by @d3liaa as component in https://github.com/noi-techpark/it.bz.opendatahub.databrowser/pull/355

- QuickView https://databrowser.opendatahub.testingmachine.eu/dataset/quick/tourism/v1/ODHActivityPoi/smgpoi107#gps-data
- DetailView https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/ODHActivityPoi/smgpoi107#gps-data

**Comment by sseppi** [comment]
@gappc and @d3liaa nice work.
I noticed that the GPS coordinates aren't editable. Is it right?

**Comment by gappc** [comment]
@sseppi yes that's correct. I think for edit capabilities we need further discussions.

**Comment by sseppi** [comment]
A dedicated issue to modify GPS coordinates has been created: #360 .
