### ISSUE TITLE
#7756: Bedeutung von einigen Attributen der Wetter API

### ISSUE THREAD

**Issue by d3liaa** [noi-techpark/it.bz.opendatahub.databrowser#172]
We asked the province about some Attributes in the weather API that aren't described in their documentation.

- [x] Update the issue with the link ( https://meteo.provincia.bz.it/stazioni-meteo-valle.asp ) @BlueRyse 
- [x] we received the full name of the attributes we requested
- [x] Create documentation (https://docs.google.com/spreadsheets/d/1Gryq2eyWa36mkkuiayLzIT7mMouxALMReudAj2mYg-E/edit#gid=924508651) @BlueRyse
- [x] Open PR to describe these attributes in the swagger (https://github.com/noi-techpark/odh-api-core/pull/325) @BlueRyse 
- [x] Check if the descriptions in the docs are valid (ticket 7756) @BlueRyse 
- [x] Open a PR to improve current descriptions and add some more (https://github.com/noi-techpark/odh-api-core/pull/326)

**Comment by BlueRyse** [comment]
Some of the attribute are still unknown since they are not in the link. These are:

1. hs
2. q
3. w
4. wMax
5. wt

**Comment by sseppi** [comment]
@BlueRyse and @lukmay I found some more details on the Open Data Portal of the Province of Bolzano:
http://daten.buergernetz.bz.it/it/dataset/p-bz-southtyrolean-weatherservice-weatherstations
The information I found are at the following link:
http://daten.buergernetz.bz.it/it/dataset/p-bz-southtyrolean-weatherservice-weatherstations/resource/78299bac-fe5a-4c46-a8b4-87d743735828
It seems that some of this parameters are for the "Stazioni idrometrice" and in particular:
- **W** is Livello idrometrico (cm)
- **Q** is Portata (m³/s)
- **tW** is Temperatura dell'acqua (°C)
It seems that some of this parameters are for the "Stazioni meteorologiche in montagna" and in particular:
- **hs** is Altezza neve al suolo (cm)

For the remeaning two, making reverse engineering starting from an applcation I did at home to manage the watering in my garden, it seems that:
- **gs** is the global radiation
- **wMax** is the gust speed

**Comment by BlueRyse** [comment]
@sseppi Thanks Stefano, I will add these description to the sheet, and if you think it's okay I can also make a PR to the API core to show the descriptions in the swagger

**Comment by BlueRyse** [comment]
@sseppi One more thing, did you mean wt, insteand of tw?

**Comment by sseppi** [comment]
@BlueRyse in the documentation they write `tW` but in the JSON there is onli `wt`. So I suppose that the documentation has a spell error...

If you want, you can post a question at the Meteo Service at the following email: meteo@provinz.bz.it

If we have all information now we can go on with the PR.

**Comment by BlueRyse** [comment]
@sseppi Perfect, PR opened here: https://github.com/noi-techpark/odh-api-core/pull/325

**Comment by BlueRyse** [comment]
@sseppi With the answer from the weather province service, I improved some existing descriptions and added some more. The PR can be viewed here: https://github.com/noi-techpark/odh-api-core/pull/326

**Comment by sseppi** [comment]
@BlueRyse thank you for the PR! Let @RudiThoeni check the PR and then, if everything is ok, we can close the issue.
