### ISSUE TITLE
As a Open Data Hub PM I want that all Edit View configuration are configured in order to provide a better experience to the Data Browser users.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#174]
- [x] @d3liaa will create the spreadsheets to be used as source for the configuration
- [x] @RudiThoeni will provide at Ilaria and Delia the same rights as Sergio and Lukas on testingmachine
- [x] @BlueRyse Ask Paul if we need a new structure or we can consider the detail one 

**Deadline:** 30 November 2022
Components to configure 

- [x] imagecell (all) @d3liaa working on it
- [x] date- date picker (all)
- [x] tags/array (all)
- [x] GPS (non editable anyway?)
- [x] all about webcam details
- [x] All thinghs releted to events
- [x] Season/ Opening hours
~Max Seating Capacity (gastronomy)~ => Gastronomy is deprecated, no need to implement component
~Category (gastronomy)~ => Gastronomy is deprecated, no need to implement component
~Facilities (gastronomy~) => Gastronomy is deprecated, no need to implement component
~Dishrates (gastronomy)~ => Gastronomy is deprecated, no need to implement component
~Ceremony Codes (gastronomy)~ => Gastronomy is deprecated, no need to implement component

Edit views

- [x] Ski Area
- [x] Ski Region
- [x] Tourism Association List
- [x] Meta Region
- [x] Region
- [x] Municipality
- [x] District
- [x] Experience Area List
- [x] Activities \|POIsTwo separate(excel) | 
- [x] Accomodations
- [x] Events
- [x] Events Eurac NOI
- [x] Venues
- [x] Articles
- [x] Webcams
- [x] Gastronomy
- [x] Wine awards
- [x] Weather
- [x] WeatherHistory
- [x] Weather District
- [x] Weather in Realtime
- [x] Snow Report
- [x] Measuring Point

----------------------------------------------

Current state as of 2023-04-06:

most EditViews will be configured with merge of PR #310 

TODO:

- [x] Reconfigure following datasets
  - [x] ODHActivityPoi
  - [x] District
  - [x] MetaRegion
  - [x] SkiArea
  - [x] Venue Table and shared view
- [x] Add generalized LocationInfo (implement configuration for all 3 types)
- [ ] Related content: there is a separate issue for this: #316
- [x] Improve WebcamCell Table to show URL with UrlCell component => done with 891dde86982142899881df5f7e0c109b1c310eb7

**Comment by RudiThoeni** [comment]
assigned all roles to mennittid@gmail.com, but no user found for ilaria on testingmachine, email?

**Comment by ila131** [comment]
Right sorry, I use Delia’s user for the databrowser. So, I do not have a user @RudiThoeni

**Comment by ila131** [comment]
Now I also have a user :)

**Comment by RudiThoeni** [comment]
ok rights are assigned

**Comment by ila131** [comment]
Many thanks :)

**Comment by sseppi** [comment]
@gappc in the description there is a list of missing components found by Delia, can you please update the description by tagging the one you developed?

**Comment by gappc** [comment]
@sseppi  some components are missing in the list:

- [x] edit multi-line text
- [x] edit HTML
- [x] edit SMG Tag selector
- [x] edit technology field
- [x] edit tagging field -> not same as "tags/array (all), since array can contain string, numbers, objects....
- [x] edit Links
- [x] edit logo
- [x] edit ArticleTypes
- [x] edit AdditionalArticleInfos
- [x] upload PDF
- [x] edit ODH Tag
- [x] edit Technology Fields
- [x] edit Tagging fields

**Comment by sseppi** [comment]
@pkritzinger the goal is to have all Edit Views proper configured and online till the 15th March 2023. 

The Customer Care team told me that all Edit Views has been configured, can you please check that everything is inline with the defined UI?

**Comment by pkritzinger** [comment]
@sseppi that is fine, I'll go through the tasks after my return and provide feedback.

**Comment by sseppi** [comment]
@d3liaa During December and January it has been developed a new set of components for the Edit View.

Could you please check each dataset and, wherever necessary, integrate the new components?

**Comment by sseppi** [comment]
@pkritzinger @gappc @d3liaa as already mentioned in another issue, yesterday I had an internal meeting and there it emerged that, for our strategy, it will be important that the Data Browser have a standard behaviour for all Datasets.

For this reason we should avoid to have custom business logic (e.g. mappings of Open Data Hub Tag or SMG Tag) or texts (e.g. description of attributes) hardcoded in the Data Browser code as much as possible. All web component should be as generic as possible that every time there is the same attribute in the data can be viewed and changed in the same way (e.g. GPS coordinates should be edited always in the same way, TAG too, etc.). Please while doing this final review try to see if this is the case or if there are components that we should generalize in order to be used for all datasets.

The data browser should be simply a renderer of what he gets from the APIs without applying and logic on the data. For us it is important the the logic is demanded to the APIs.

@mrabans what do you think? did I explained well what we discussed yesterday?

**Comment by gappc** [comment]
@sseppi I think we can take a final look at the EditViews. Apart from the "Related content component" #316 it seems that all tasks of this issue are fulfilled.
