### ISSUE TITLE
As an Open Data Hub user I want the same language management for all datasets in order to reduce the complexity of maitenance of the data.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#180]
To implement this issue the tasks are:
- [x] @RudiThoeni will unify the language handling on API side for the following datasets:
  - [x] EventShort
  - [x] Venue
- [x] @gapp will implement the standard language handling for:
  - [x] EventShort
  - [x] Venue

**Comment by sseppi** [comment]
@RudiThoeni can you plese work fist on the EventShort so we can then start testing with Marion?

**Comment by RudiThoeni** [comment]
@gappc  both implementations done

**Comment by sseppi** [comment]
@gappc I think that also this issue can be closed since the language management should be the same for the entire Data Browser.

**Comment by gappc** [comment]
@sseppi yes, you can close it.
