### ISSUE TITLE
As an Open Data Hub Data Browser user I want the button "Quick View" is hided if the "Quick View" isn't configured for the dataset in order to avoid to click on it and get an error message.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#182]

**Comment by sseppi** [comment]
Maybe in this case we can evaluate weather to hide completely the button or to display it but not clickable.

@pkritzinger which way do you think it would be the best?

**Comment by pkritzinger** [comment]
@sseppi as long as **no** "Quick view" for any dataset has been configured, I would suggest to completely hide the tab. As soon as we have one or more configured "Quick views" we should show the tab everywhere to enable learning effects for the system.
If a "Quick view" has not been configured yet, the tab should be clickable and we show a status similar to: "We are working on the configuration of the Quick view of this dataset".

**Comment by sseppi** [comment]
@pkritzinger thank you for the feedback!

@gappc I agree with Paul's proposal, I would suggest to do so.

**Comment by gappc** [comment]
@pkritzinger, @sseppi: done as of https://github.com/noi-techpark/it.bz.opendatahub.databrowser/commit/09d498d776ea114e2d61361a1d615ccf3064ef16
