### ISSUE TITLE
As an Open Data Hub Project Manager I want that the information displayed in the "Dataset Overview" are provided by the metadata API in order to have always the updated version of the information and manage it in a single point.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#183]
In order to implement this issue the tasks are:
- [x] @RudiThoeni rename the `https://tourism.api.opendatahub.bz.it/v1` endpoint into `https://tourism.api.opendatahub.bz.it/v1/metadata`
- [x] @gappc intagrates the data provided by the API
- [x] @sseppi @pkritzinger @mrabans will define a list of information to be displayed in the Overview
- [x] @RudiThoeni will integrate the missing data in the API
- [x] @gappc will update the view with the new data

**Comment by RudiThoeni** [comment]
duplicate of #184 https://github.com/noi-techpark/it.bz.opendatahub.databrowser/issues/184

**Comment by sseppi** [comment]
@gappc the beta version of the Data Browser does already take the data from the metadata API or is still hardcoded?

**Comment by gappc** [comment]
@sseppi its still hardcoded, we need to discuss edge cases before I can implement it.

**Comment by sseppi** [comment]
OK, so I keep this issue open and we can discuss how to implement it in one of the next iterations.

**Comment by sseppi** [comment]
During the meeting we decided to:
- put in testing the Dataset Overview that takes the data from the metadata API
- we need to improve the contents that the metadata API provides 
- we show only the data and information that can be retreived from the APIs (no hardcoded data has to be included)

**Comment by sseppi** [comment]
@gappc I tried to change the NOI Article Metdata at the following link:

https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/MetaData/it.bz.opendatahub.article.noi

The description and other fields are updated properly, but the name of the dataset is always Articles only (See result at the link below). It seems that the dataset gets always the generic name of the Endpoint and not the name defined in the MetaData API.

https://databrowser.opendatahub.testingmachine.eu/dataset-overview/it.bz.opendatahub.article.noi

Can you please check?

**Comment by gappc** [comment]
@sseppi what do you refer to as "name", do you mean the "Shortname"? That one seems to update correctly.

If you mean the title shown in the dataset-overview, that one is taken from the field "ApiIdentifier", but that field again is a candidate for automatic menu creation (see #204), so it wouldn't be a good idea to change that one.

@RudiThoeni what fields in the MetaData API are intended for what use? At the moment, the mapping can be seen here: https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/50de720336b3546b7f28bf8f7596b6f76d46e93b/databrowser/src/domain/metaDataConfig/tourism/useMetaData.ts#L47-L64

**Comment by sseppi** [comment]
@gappc I mean the title in the dataset-overview. In my opinion we have to find a way to have different titles for different datasets. As you can see from the screenshot below actullay, if I'm not wrong, we have 3 different Articles (IDM Articles, NOI Articles and Articles) and the user doesn't understand which is the difference from the Title. He has to read the description and this isn't optimal.

![Schermata da 2023-02-24 08-17-10](https://user-images.githubusercontent.com/7909989/221116294-44439176-51be-4cdc-9a63-3ea9e34cd0ec.png)

We have to consider this also in the automatic menu creation and understand were to take the information we need since the menu must be consistent with the dataset-overview.

I remember that one idea emerged during the las collaudo with Patrick was also to show the correlation between the Datasets and the Endoints by putting in the Datasets the following information:
- **Title**: Dataset Name (e.g. NOI Articles)
- **Subtitle**: From Endpoint Name (e.g. Articles)


> @sseppi what do you refer to as "name", do you mean the "Shortname"? That one seems to update correctly.
> 
> If you mean the title shown in the dataset-overview, that one is taken from the field "ApiIdentifier", but that field again is a candidate for automatic menu creation (see #204), so it wouldn't be a good idea to change that one.
> 
> @RudiThoeni what fields in the MetaData API are intended for what use? At the moment, the mapping can be seen here:
> 
> https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/50de720336b3546b7f28bf8f7596b6f76d46e93b/databrowser/src/domain/metaDataConfig/tourism/useMetaData.ts#L47-L64

**Comment by gappc** [comment]
@sseppi the mapping you mentioned makes sense, but I suggest to use a term different than `Subtitle` for the mapping from `ApiIdentifier`, because `Subtitle` could be misleading (I would not suspect `Subtitle` to contain information about the underlying endpoint). Instead, we could reuse the term `ApiIdentifier`, or something that hints properly at what the data contains.

The next question would be on how to display that information in:
- dataset-overview
- dataset-overview for single record
- Dataset name in Table-, Detail-, Edit-, RawView

@sseppi, @pkritzinger what do you say?

**Comment by sseppi** [comment]
> @sseppi the mapping you mentioned makes sense, but I suggest to use a term different than `Subtitle` for the mapping from `ApiIdentifier`, because `Subtitle` could be misleading (I would not suspect `Subtitle` to contain information about the underlying endpoint). Instead, we could reuse the term `ApiIdentifier`, or something that hints properly at what the data contains.

My was just a proposal to explain the goal we have to achieve.
I'm sure that @pkritzinger will find a better way to manage this information.

> 
> The next question would be on how to display that information in:
> 
>     * dataset-overview
>     * dataset-overview for single record
>     * Dataset name in Table-, Detail-, Edit-, RawView
> 
> @sseppi, @pkritzinger what do you say?

Maybe one idea could be to have a Title like "NOI Articles from Articles" having the from Articles smaller?

**Comment by gappc** [comment]
@sseppi yes that could work. @pkritzinger, @Mazzolintis what do you say?

**Comment by pkritzinger** [comment]
@sseppi @gappc this could all work pretty well. 
Looking back to the discussions going on about the Metadata-API, from my point of view we definitely need to have a look at the optimization of the navigation now.
#204 #278 

I would prefer that we created a concept for the navigation and then define the structure of the metadata-api for the navigation. 
Ok for you?

**Comment by RudiThoeni** [comment]
For: @RudiThoeni what fields in the MetaData API are intended for what use? At the moment, the mapping can be seen here:

Erklärung der Felder

- Id --> Metdadata Id
- ApiVersion --> Version Api (v1)
- ApiFilter --> Filter um zu diesen dataset zu kommen (z.B source=siag, oder tagfilter=gastronomy etc...)
- ApiUrl --> Url des Endpoints (wird falls ApiFilter vorhanden ist mit diesem ergänzt)
- ApiIdentifier --> Endpointname
- ApiDescription --> Beschreibung in de,it,en (Bisher nur en überall vorhanden)
- Deprecated --> bool, dataset deprecated ja/nein
- Sources --> welche Quellen gibt es hier Array mit quellenkürzel
- ApiAccess -->  Da für jede Quelle unterschiedliche Daten geliefert werden hier als Dictionary immer mit quellenküzel --> open/reduced/closed (open = opendata, closed = closeddata, reduced = zwar auch opendata aber reduzierter datensatz von quelle LTS)
- Output --> was gibt die api für ein format zurück (default hernehmen alles andere ist zusatz)
- PathParam --> hab ich hier (https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/development/databrowser/src/config/config-for-pages.ts) gesehen z.B für https://api.tourism.testingmachine.eu/v1/Weather/District  ist PathParam: ["Weather","District"],
- Recordcount --> zählt die open/closed/reduced Datensätze.....  ist so zu vestehen, wie gesagt die reduced datensätze sind auch opendata
- OdhType --> Typ des datensatz im odh (unter _Meta Objekt)
- SingleDataset --> einzelnes Dataset ja/nein

**Comment by mrabans** [comment]
Just to not forget the input from todays meeting on the strategy: We should add a datetime attribute "created" to know when this endpoint was created and activated.

**Comment by sseppi** [comment]
> Just to not forget the input from todays meeting on the strategy: We should add a datetime attribute "created" to know when this endpoint was created and activated.

@mrabans this is the picture of what we have at the moment in the Metadata API. For the future developments we do have a dedicated issue: #184 (I already added there )

In this iteration I would do the best we can with the actual API version. In the new issue we have to collect all the needs we have and then plan the improvement of the Data Browser together with the development of the APIs.

**Comment by mrabans** [comment]
Sure, thanks!

**Comment by gappc** [comment]
@sseppi: do we have a decision on what to do? If so, could you please describe it shortly? Otherwise I suggest that we discuss this topic in detail where we gather the requirements regarding MetaData API (navigation, menu, dataset-overview, dataset labels / title, deprecation, ...?) and come up with a solution to implement.

**Comment by sseppi** [comment]
@gappc in my point of view in this issue we have only to fix the Title and my suggestion would be the following:

"`Shortname` from `ApiIdentifier`" the exmaple for the NOI Articles will be:  "NOI Articles from Articles"

And I would use the same structure all Views (e.g. dataset-overview, dataset-list, table, detail, edit, etc.)

@pkritzinger and @Mazzolintis do you agree?

For all other things you mentioned we have lready dedicated issues /discussionsto be implemented in the next iterations:
- navigation and menu: #278 
- dataset-overview: #184
- dataset labels/deprecation: https://github.com/noi-techpark/it.bz.opendatahub.databrowser/discussions/307#discussioncomment-5121983

**Comment by pkritzinger** [comment]
@sseppi yes, that sounds good.

**Comment by sseppi** [comment]
Top, so I would suggest that @gappc implements this logic for the title:

"`Shortname` from `ApiIdentifier`" the exmaple for the NOI Articles will be:  "NOI Articles from Articles"

And I would use the same structure all Views (e.g. dataset-overview, dataset-list, table, detail, edit, etc.)

Then we close this issue and we keep going on with the other topics in the respective issues.

**Comment by pkritzinger** [comment]
thanks @gappc 
Would it be possible to always use regular font style for "from `ApiIdentifier`"? Would increase legibility especially on table view and detail/edit/ raw view from my point of view.

**Comment by sseppi** [comment]
Thanks @gappc 

Nice work, can we use the same logic also in the "List of all datasets" page?

https://databrowser.opendatahub.testingmachine.eu/dataset-overview

In my opinion it would help the users in finding the right dataset they are looking for.

**Comment by pkritzinger** [comment]
@sseppi already exists - at least for some datasets:
![image](https://user-images.githubusercontent.com/92454516/226847457-cc8dbf53-57e7-4971-8e7d-e422ce380a8a.png)

**Comment by sseppi** [comment]
@pkritzinger thank you, so probably it was a cache problem on my side. Sorry for that.

Regardin the proposal of paul we can try to increase the "from `ApiIdentifier`" part. But I would like that in any cse the user is able to distinguish the name of the Dataset from the name of the Endpoint or parent Dataset.

@pkritzinger how would you suggest to do that?

**Comment by gappc** [comment]
@sseppi this should not

**Comment by gappc** [comment]
Sorry, i

**Comment by gappc** [comment]
Sorry, I clicked on the wrong button and closed the issue

**Comment by gappc** [comment]
@sseppi this should not be a caching issue, please look

**Comment by sseppi** [comment]
@gappc now it works, befor I searched for NOI articles and I wasn't able to find it... But now it works. Thank you

**Comment by sseppi** [comment]
OK. If possible let do this change and the we can close the issue.

**Comment by gappc** [comment]
@sseppi, @mrabans, @pkritzinger: done as of 368cd970aa26981b7631661cc9eecd05b423b483, you can take a look here:

https://databrowser.opendatahub.testingmachine.eu/dataset-overview/it.bz.opendatahub.article.noi
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Article?source=noi
If it's ok, please close the issue

**Comment by pkritzinger** [comment]
@gappc awesome, thanks. can be closed from my pov

**Comment by sseppi** [comment]
Super! Congratulation for the great work.
