### ISSUE TITLE
As an Open Data Hub Project Manager I want that the information displayed in the "Dataset Overview" are managed through the Data Browser in order to have only one point to update the metadata.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#184]
Tasks to complete the issue:
- [x] @RudiThoeni adds to the `https://tourism.api.opendatahub.bz.it/v1/MetaData` API the POST and PUT functionality;
- [ ] @pkritzinger @sseppi @mrabans define the procedures the UI/UX
- [x] @gappc implements the possibility to edit the metadata in the Data Browser

**Warning:** we have to be careful in the management of the roles that can edit this information.

Here follows a list of information that we should consider to manage in the metadata:
- Dataset name
- Data set description
- Key words/Tags
- List of sources
- Licese/Availability of data
- Number of available record
- Output type
- API version 
- API link
- Swagger link
- contact email
- links to documentation (each link must have: title, short description and link)
  - video tutorial
  - wiki pages
  - etc.
- snippet code
- web component preview (if available)
- created (date of the first creation of the Endpoint/Dataset)

**N.B.** by using this feature the Open Data Hub - Data Browser manager I want the have the possibility create more datasets starting from an original Data sets

An interesting example is the Environmental Data Platform of Eurac that you can see at the following link:
https://edp-portal.eurac.edu/discovery/
https://edp-portal.eurac.edu/discovery/16367c6a-534a-11ec-b0a3-02000a08f41d

**Comment by RudiThoeni** [comment]
extended metadata api and added POST PUT DELETE Endpoint
https://api.tourism.testingmachine.eu/v1/Metadata

**Comment by gappc** [comment]
As of #290 the correct path to the MetaData API is `/v1/MetaData` (please note the uppercase "D")

**Comment by gappc** [comment]
@sseppi you can modify the data of the MetaData API through the Data Browser (if you have the correct permissions), see https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/MetaData/it.bz.opendatahub.accommodation

Should we close this issue?

**Comment by sseppi** [comment]
Hi @gappc ,

before closing this issue I would like to discuss in the group it it makes sense to provide the edit also in the Dataset Overview page, see example below:

https://databrowser.opendatahub.testingmachine.eu/dataset-overview/it.bz.opendatahub.accommodation

**Comment by pkritzinger** [comment]
@sseppi you mean integrating a button linking to the edit-view of the dataset?

**Comment by sseppi** [comment]
@gappc thank you for the implementation, I will tet it and let you know in case of need.

@pkritzinger not only, in my point of view while closing this issue we have to open 2 new one. The first one for the extension of the Metadata Information we need to manage in this section. The second one to simplify the process to modify the data. A first way could be to add the button that links to the Edit View but, in the navigation simplification, we have also to consider in general if we reaaly need a detail view and an Edit view, or if we can use the same view just enabling or disabling the edit mode with a toggle.

**Comment by pkritzinger** [comment]
@sseppi ok, thanks for the explanation.
that's fine, I like your suggestions. As you mentioned it would be great if you could reorganize these enhancements in new issues.

**Comment by sseppi** [comment]
@pkritzinger I created the two issues:

- the issue to update the MetaData API: #332
- the issue about simplifying the editing of data: #333

**Comment by sseppi** [comment]
@pkritzinger I created the two issues:

- the issue to update the MetaData API: #332
- the issue about simplifying the editing of data: #333
