### ISSUE TITLE
As an Open data Hub Data Browser user I want a nice way to access all dataset (also the not configured one) to easily see all Open Data Dub datasets available

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#187]
As can you see in the following link, in the _Dataset Overview_ we are now displaying 16 Datasets:
https://databrowser.opendatahub.testingmachine.eu/dataset-overview
The decision of the group fr the actual MVP was to show the same tourism datasets displayed on the Open Data Hub website:
https://opendatahub.com/datasets/
In the next iterations we should display in the  _Dataset Overview_ all dataset provided in the "Dataset Metadata API":
https://tourism.api.opendatahub.bz.it/v1/metadata
Moreover we should also provide the possibility to the user to see all datasets, also the one that hasn't been configured yet and that aren't retrieved by the "Dataset Metadata API"

Tasks:
- [x] @sseppi @mrabans @pkritzinger has to define the UI/UX
- [x] @gappc implements the UI/UX defined

**Comment by sseppi** [comment]
I think we can close this issue and open a new one for the improvements (e.g. adding more information to the page and so on)

**Comment by gappc** [comment]
@sseppi can this be closed?

**Comment by sseppi** [comment]
@gappc as said in the comment of 2 days ago, from my point of view we can close the issue!

**Comment by gappc** [comment]
@sseppi sry, didn't see you closed it already :+1:
