### ISSUE TITLE
things to fix on the databrowser

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#190]
- [x] **webacam** Area id is visible as an array
- [x] **webcam** use the url cell in the detail view also
- [x] **venue** shows no data
- [x] **accomodation** use new gps cell component
- [x] **POI** fix the date format in the seasoning opening hours
- [x] **POI** removed related content (NO, is still needed for edit view)
- [x] **Municipality** remove image from list view as it gives almost always an error
- [x] fix active label on some datasets detail view
- [x] **events** fix topics visualization in events detail
- [x]  **NOIEvents** rooms visualization (maybe create a vue component)
- [x] gps visualization

navigation
- dis & mun only shows municipality (maybe separate the two?) in the 'all the datasets page'

has only GENERATED config
- area
- locations
- activity
- ski area list
- points of interest
I understand why these are only generated is just to document it 
- accommodation features
- activity types
- gastronomy types 
- venue types
- NOI Events by room occupation
- OdhTags

**Comment by gappc** [comment]
@sseppi can this be closed?

**Comment by gappc** [comment]
@sseppi can this be closed?
