### ISSUE TITLE
As a user, I would like to access a list of all datasets within the databrowser - also the not-configured ones and the ones not having a description.

### ISSUE THREAD

**Issue by pkritzinger** [noi-techpark/it.bz.opendatahub.databrowser#199]
Reimplement access to the list that was already available on the previous version of the databrowser.

**Comment by sseppi** [comment]
OK

Thank you @pkritzinger for the answer. If I understood well your suggestion is to add a Link to the dataset overview and to the menu tu acecss a page with the list of all datasets (configured and not). right?

If so, I would ask to @gappc to do so, and then we will optimize it during the next iteration.

**Comment by gappc** [comment]
@pkritzinger, @sseppi: the page is still there: https://databrowser.opendatahub.testingmachine.eu/links

I have now added a link to the dataset overview (in the header) and menu (as last item). Please take a look at it.

**Comment by pkritzinger** [comment]
@gappc thanks a lot, looks good from my point of view.
@sseppi what do you think?

**Comment by sseppi** [comment]
Fine for me as well!
Thank you all for the quick answers and reaction.
