### ISSUE TITLE
Some image links don't work properly, because they link to HTTP

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#207]
Example: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Weather

In the picture below you see that the image in the IMAGE column is not loaded, because it refers to a HTTP address (http://daten.buergernetz.bz.it/services/weather/graphics/maps/meteomap0/78406/en), while the Data Browser itself is delivered via HTTPS. Most modern browsers (and browser addons focused on security) refute to load content from HTTP, if the page itself is loaded via HTTPS.

We need to think about strategies on how to fix HTTP issues. The best solution for the example mentioned above would be for daten.buergernetz.bz.it to deliver its data via HTTPS with a valid certificate, which is the current state of the art.

![image](https://user-images.githubusercontent.com/5732768/200620856-8073ef57-5a1e-4a84-a9c3-8cf440abb5ab.png)

**Comment by sseppi** [comment]
It seems that after notifying the Data Provider, they updated the SSL certificate.

Now the images are working again, I close the issue.

@gappc in case you notice the problem again, let me know
