### ISSUE TITLE
As a customer care member I would need the check of some terms and acronyms used in the Data Browser 2.0

### ISSUE THREAD

**Issue by emilylouisesimonis** [noi-techpark/it.bz.opendatahub.databrowser#215]
**1) We should try to keep all descriptions as generic as possible and avoid limiting the geography to South Tyrol.** 

An example: "This is the Data Browser of the Open Data Hub of South-Tyrol" should be modified as follows: "This is the Data Browser of the Open Data Hub"

**2) We should always try to avoid acronyms**
- always prefer the full name 'Open Data Hub' to 'ODH', unless (of course) it is strictly necessary (e.g. ODHTags)

**Comment by sseppi** [comment]
@gappc I would assign these activities at Ilaria and Delia. In your opinion, are Ilaria and Delia able to verify and correct everything autonomously?

**Comment by gappc** [comment]
@sseppi I think from a technical perspective they will be able to correct the stuff but they need support from NOI to understand what and how to correct.

**Comment by sseppi** [comment]
@d3liaa and @ila131 can you please do the same checks you did for the Open Data Hub website? In case of need feel free to contact me.

**Comment by ila131** [comment]
Yes, sure :) @sseppi

**Comment by sseppi** [comment]
@ila131 as far as I remember you did the check and we can now do a final review and then close this issue. right?

**Comment by ila131** [comment]
@sseppi Yes, exactly!
