### ISSUE TITLE
Set gzip compression on server

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#258]
At the moment, neither the TEST (https://databrowser.opendatahub.testingmachine.eu/) nor the PROD (https://v2-beta.databrowser.opendatahub.com/) environments deliver the responses with gzip compression on.

You can verify that if you take a look e.g. at the response of https://v2-beta.databrowser.opendatahub.com/ (using curl):

`curl -i 'https://v2-beta.databrowser.opendatahub.com/' --compressed'`

You'll see, that the header `Content-Encoding: gzip` is missing, which indicates that the response is not zipped.

Please compare that to the output of e.g. https://opendatahub.com/ (using curl):

`curl -i 'https://opendatahub.com/' --compressed`

That response contains a `Content-Encoding: gzip` header.

@dulvui: could you please configure gzip compression for the Data Browser In TEST and PROD?

**Comment by dulvui** [comment]
@gappc I think that the compression is set on our proxy because on the AWS S3 bucket I can't set any compression. I saw that websites that run on our old proxy like opendatahub.com have compression enabled and the sites that run on our new proxy don't.
Is this urgent? Then I can simply switch to our old proxy provider, otherwise I would try to set compression also on our new proxy, but that could take me some days.

**Comment by gappc** [comment]
@dulvui thank you for that information. In my opinion it is not urgent, but it should be on our TODO list. @sseppi: what do you think about it?

**Comment by gappc** [comment]
Hey @dulvui, any update on this issue?

**Comment by dulvui** [comment]
@gappc We are migrating everything to our new proxy, so this might solve the problem.
I will let you know, when the migration is done, so we can check if the gzip problem still exists there.

**Comment by gappc** [comment]
@dulvui sounds good, do you have any idea when this may be available?

**Comment by dulvui** [comment]
@gappc I can't give you a timeline, but @clezag is working on our new proxy right now so he might be able to give your more info on this.

**Comment by gappc** [comment]
Hi @clezag, gzip compression works great, but there is a slight problem when loading a page other than the home page, e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation

If you look at the network tab you'll see that the initial request is returned with a 404 status AND the the content of index.html, which seems a bit odd (see image below).

Since the Data Browser is a SPA (Single Page Application), it should return a 200 status with the content of index.html and let the website decide if the route is known.

![image](https://user-images.githubusercontent.com/5732768/228871362-6ac11ae9-4e03-45ad-89cd-b0486d978fda.png)

Could you please take a look at it? Thx

**Comment by clezag** [comment]
The static website is hosted on an S3 bucket, which is configured to return index.html on error, which is why it returns a 404 (doesn't find the /dataset/... URL in the bucket), but also the content.

I don't see any options on the bucket side to fix this, and I assume the problem only presents itself if you press F5 or enter a URL that includes a local route.

**Comment by gappc** [comment]
@clezag this is problematic behavior, because 404 means the document doesn't exist. It's just an implementation detail of most browsers that they show the response content regardless of status code, but that's not guaranteed and other tools (browsers?) may fail.

I see that the requests are returned by a Caddy instance, the response contains a header "server: Caddy". Do you have access to Caddy and its configuration?

What about the proxy mentioned by @dulvui in a comment above? Perhaps you could rewrite requests there?

Another option seems to be to use CloudFront (see e.g. https://medium.com/@P_Lessing/single-page-apps-on-aws-part-1-hosting-a-website-on-s3-3c9871f126), do you use CloudFront or something similar?

What other options do we have? Could you send me some high-level details about your architecture?

**Comment by clezag** [comment]
Currently it's just Browser -> Caddy -> S3 bucket

Technically the backend is behaving correctly, as the requested file does indeed not exist, it's more the SPA practice of local routing being ultimately a hack.

Theoretically we could add a bunch of rewrite rules to Caddy, but we'd like to avoid cluttering a simple reverse proxy with a bunch of application specific rules.

Since this looks like a general Issue with S3 hosted websites (which we have many of), we'll discuss this internally and let you know when we've come to a solution

**Comment by clezag** [comment]
In the meantime, @gappc could you please provide us with an (informal) set of rewrite rules, that is the URL patterns which should always point to index.html?

**Comment by gappc** [comment]
@clezag strongly disagree with "SPA practice of local routing being ultimately a hack", but lets not start that discussion.

Having Caddy as reverse proxy should allow you to add the correct behavior, but I'm not 100% sure how to do it because I'm not very familiar with Caddy and I don't have access to your config. How about `try_files` (see https://caddy.community/t/how-to-serve-a-single-page-app-spa-with-caddy-2/12770)? Would it work with S3?

If it does not work, then we have at least two other possible solutions:

1. If a response returns from S3 with 404, then rewrite the response status code to 200. Rationale: resources that are not found on S3 return a 404, the document returned for 404 is index.html. Applying this rule returns the index.html with status code 200 for resources that are unknown, that's what we want
2. rewrite all requests that **DON'T** match any of the following paths:
- `/*` => don't rewrite requests to resources in root (which contains the files from folder [databrowser/public](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/tree/development/databrowser/public))
- `/assets/**` => don't rewrite requests to the folder `assets` and any of it's sub-resources (contains the compiled JavaScript files)
- `/fonts/**` => don't rewrite requests to the folder `fonts` and any of it's sub-resources (contains fonts)
- `/home/**` => don't rewrite requests to the folder `home` and any of it's sub-resources (contains just images at the moment, maybe it would be better to rename it to `images` if we go with this solution)

If `try_files` does not work, I'd opt for solution 1 because it's simple and we don't have to keep the exempt rules in sync with the project (although the list should not change that often).

Please let me know if you have further questions.

**Comment by clezag** [comment]
@gappc I've moved the hosting from S3 to a nginx container (for now only testing).
This allowed us to fix the 404 issue, and gives us flexibility should we ever need more advanced configurations (the nginx config is in the repo).
Let me know what you think, so we can eventually do the same in production

**Comment by gappc** [comment]
@clezag nice work, thank you :+1: 

One note: I saw that the fonts are not zipped. Could you please add them to the gzip compression config? The font file format is `ttf`.

Otherwise, the change looks good to me and could be deployed to production.

Just out of curiosity: I noted that there are still two `server` headers in the response: `Caddy` and `nginx/1.23.4`. If I understand this right, the current setup uses nginx + Caddy. Do we need both servers or would it be enough to have only one, given that the hosting doesn't involve S3 anymore?

**Comment by clezag** [comment]
@gappc 
I've added the mime type to the gzip list. For future additions or changes to the nginx config, you can just modify infrastructure/nginx/default.conf yourself and git push, the config file will be loaded by the container by the CI/CD action.

You are correct, both Caddy and Nginx are in use. 
Caddy is used solely as a reverse proxy and handles all the SSL and certificate stuff, while the site itself is hosted on nginx, which is inaccessible to the public. 
This is just how we set up all our https sites, so while it might technically be superfluous in the case of nginx, it has the benefit of being in line with our standard architecture and tooling.

**Comment by gappc** [comment]
@clezag thank you for the change, unfortunately it doesn't work as expected (no gzip compression for fonts). Given that we can modify the nginx config, I'll give it a try.

If it's ok for you, we can close this ticket.

**Comment by gappc** [comment]
@clezag sorry to bother you again, I found the reason that fonts are not delivered with gzip compression: the `ttf` file ending is not defined in nginx's `mime.types` file. So I see two solutions and I would like your opinion on how to solve the problem:

1. we could add a `location` in the `default.conf` file for `/fonts/` that just compresses anything from that folder:
```
    location /fonts/ {
        gzip_types *;
    }
```
2. we could extend / overwrite the `mime.types` file with an entry for `ttf` files

What do you think would be the preferable solution?

**Comment by gappc** [comment]
@clezag looks very good now, I see that a full home page reload with empty cache requires ~800KB instead of ~2.2MB and if the resources are cached, we get down to ~14KB. Very nice, thank you :+1:
