### ISSUE TITLE
As a Data Browser User I want that the Toggle changes colour when active/inactive, to better understand the status of it.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#266]
While testing some users provided the feedback that is difficult to understand if a Toggle is active or inactive.

The proposal is to change the colour of the toggle as follows:
- Red: when the toggle is inactive
- Green: when the toggle is active

**Comment by gappc** [comment]
@sseppi should be resolved, please check.

**Comment by sseppi** [comment]
The issue is resolved now, let see what the users says.
