### ISSUE TITLE
"new" config for EventShort

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#267]
The button "Add new record" doesn't work this feature should be implemented.

**Comment by gappc** [comment]
@sseppi this feature is now implemented such that it works, but it can be improved. We should talk about how "new" views should look like:

- which fields are mandatory
- which fields should be shown in the new view
- order of fields / categories

In my opinion, we can close this ticket an add a new one, where we define how "new" views should look like and behave.

**Comment by sseppi** [comment]
@gappc let discuss this issue in the sprint meeting, I think I didn't get what you mean.

**Comment by sseppi** [comment]
We decided to keep the view as it is and change it in case of request from the content editor
