### ISSUE TITLE
Edit View: Empty ODH tag table

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#271]
Observed: Empty ODH tag table (and other components like technology fields) does not give any system feedback. Expected: should work as for images: https://prnt.sc/G55kJoxDS4Iw

**Comment by sseppi** [comment]
@pkritzinger QUESTION (not sure what is meant, may be fixed?) => “No images have been uploaded yet”

**Comment by pkritzinger** [comment]
@sseppi this question has been solved in the discussion with Christian yesterday.

**Comment by sseppi** [comment]
@pkritzinger you are right, I misunderstood the sentence in the document.

The answer was to add the following sentence "No images have been uploaded yet"

**Comment by gappc** [comment]
@sseppi should be resolved, please check.

**Comment by sseppi** [comment]
In my opinion seems to be fine, @pkritzinger can you please double check ?

**Comment by sseppi** [comment]
The solution is fine like it is for now
