### ISSUE TITLE
Accommodation Edit View: Fields "Features", "Special Features" and "Badges" are not editable

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#272]
Observed: Empty fields don't seem to be editable in the Accomodations-Dataset (https://prnt.sc/JfmBRIQCV-5c) Expected: also empty fields are editable.

**Comment by sseppi** [comment]
QUESTION: these are ordinary array fields, should we use something like the tag component? 

ANSWER: yes, use something like table component

**Comment by gappc** [comment]
Update: The fields "Special Features" and "Badges" are now editable; the field "Features" seems to be a getter and can thus not be edited.

@RudiThoeni: can you please explain how to set the "Features"?

**Comment by RudiThoeni** [comment]
Hi Christian

Features  --> Populated on Import from LTS, filled with various information on import.... Has already a getter
This field was introduced later so i added it directly with a GET/SET without this logic from below (example BadgeIds (get;set), AccoBadges (get) ;)


Explanation of the other fields (get;set;) (think you know it already)

- BadgeIds [string list] --> on import there is a logic that populates this array (certain rules)
- SpecialFeaturesIds [string list] --> on import there is a logic that populates this array (certain rules on if a combination of certain Features is there etc...)
- ThemeIds [string list] -->on import there is a logic that populates this array (certain rules) 
- AccoTypeId [string] 
- AccoCategoryId [string]
- BoardIds [string list]

The new fields (only getter) with the self links are:

- AccoSpecialFeatures  --> GETTER on SpecialFeaturesIds
- AccoBadges --> GETTER on BadgeIds
- AccoThemes --> GETTER on ThemeIds
- AccoType --> GETTER on AccoTypeId
- AccoCategory --> GETTER on AccoCategoryId
- AccoBoards --> GETTER on BoardIds

**Comment by RudiThoeni** [comment]
I saw on the Edit Component for Accommodation type, there is something with Accommodation type + ACcommodation category
![image](https://user-images.githubusercontent.com/30471361/215441675-2389f876-8c78-4317-bac4-4d89caf1bf71.png)

I think the Unknown Value is there because of using the "Id" property instead of the "Key" property of at example https://tourism.api.opendatahub.com/v1/AccommodationTypes/BedBreakfast

**Comment by gappc** [comment]
@RudiThoeni: first of all, thanks to highlight the wrong configuration for accommodation type and category, I fixed it now ;)

Regarding the getters/setters: is my understanding correct, that "Features" can be set only through the "Features" field? I also saw, that there seems to be no get-all endpoint for the feature, is this correct? For example:

- https://api.tourism.testingmachine.eu/v1/AccommodationFeatures/C1A8A40E353346E98CF6FA81F769F690 -> points to the feature with ID `C1A8A40E353346E98CF6FA81F769F690`
- https://api.tourism.testingmachine.eu/v1/AccommodationFeatures -> does not exist

Would it be possible to:

1. add the https://api.tourism.testingmachine.eu/v1/AccommodationFeatures endpoint? That way we could show all possible options to the user
2. add a default getter / setter field for "Features" (e.g. FeaturesIds), like for "SpecialFeatures" (SpecialFeaturesIds) and "Badges" (BadgeIds) as that seems to be the standard in ODH to cope with such entries. Or would it be better to agree to another standard and update all relevant fields in all datasets to that one?

**Comment by RudiThoeni** [comment]
Hi @gappc 

1)
https://api.tourism.testingmachine.eu/v1/AccommodationFeatures  needed Authorization so now i removed this check.... hopfefully this will not cause problems with our dataprovider
2)
Correct, Features has a GET/SET, it is an Object (AccoFeatureLinked) List, 
The Id, Name  properties are filled from AccommodationFeatures  Id + TypeDesc["en"], The other stuff like HgvId, OtaCodes, RoomAmenityCodes is filled on import by some xml mapping lists.....

If it is possible a component should fill 
Id, Name and let the other stuff like HgvId, OtaCodes, RoomAmenityCodes etc...  as free editable
If not possible let all as free editable

This field will never be edited in the databrowser so let us not invest to much effort in it....

**Comment by gappc** [comment]
@RudiThoeni thank you for the explanation. If I understand correctly, you propose to as "Features" non-editable.

@sseppi if that's the case, should we close this issue, as "SpecialFeatures" and "Badges" are now editable? You can find an example record here: https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/Accommodation/2657B7CBCB85380B253D2FBE28AF100E
