### ISSUE TITLE
Edit View: it is not possible to change the order of some table components

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#273]
Observed: it is not possible to change the order of some table components (e.g. additional information for articles and links in articles). Expected: change order of table components.

**Comment by gappc** [comment]
@sseppi duplicate of #74, can we close this issue?

**Comment by sseppi** [comment]
As far as I understand the issue #74 regards the Column size and this one the ordering.

Let discuss this in the next sprint meeting
