### ISSUE TITLE
Table View: search no result found

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#275]
As an Open Data Hub DAta Browser user, in case there are no results fitting my search, I would like to be notified with a proper message.

As you can see in the screenshot below, the Data Browser actually doesn't provide any information.

![Schermata da 2023-01-25 15-22-47](https://user-images.githubusercontent.com/7909989/214589050-6b64b12b-2cce-4d19-8e70-5479a276c072.png)

**Comment by sseppi** [comment]
@pkritzinger shall we implement a solution similar to the one implemented for the empty tables (see issue #271 ) and show a sentence like "No results found"?

@gappc is it feasible to implement a solution like the one I proposed?

**Comment by pkritzinger** [comment]
@sseppi would be easiest for a beta-version, yes. Afterwards we should look for a optimized solution.

**Comment by sseppi** [comment]
OK, so I would ask @gappc to implement this easiest way that will be optimized with the improved version of the filters

**Comment by gappc** [comment]
@sseppi should be resolved, please check.

**Comment by sseppi** [comment]
From a technical point of view the issue is solved, but maybe we can find a better sentence to be used.

@pkritzinger what do you think?

**Comment by pkritzinger** [comment]
Here a new wording proposal @sseppi :
"We could not find any data matching to your search request. 
Our suggestions:
1. Check for typos in your search request.
2. Try to insert other terms."

**Comment by sseppi** [comment]
OK, fine for me.
@gappc can you update the sentence or do we have to create a new issue for it?

**Comment by gappc** [comment]
@pkritzinger, @sseppi there is already an issue for that: #285. I'll move the new sentence over there.
