### ISSUE TITLE
Table view: Lines per page behind the table in Brave browser.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#276]
As you can see in the screeshot below if I open the "Lines per page" switcher and the right tab (Search Filter/Export Dataset) is open, it opens behind the table and is not possible to change the configuration,

![Schermata da 2023-01-25 16-15-02](https://user-images.githubusercontent.com/7909989/214601519-ed649bd3-136c-4453-beee-c539db43ba91.png)

Operating System: Ubuntu 20.04
Browsers: 
- Brave (Version 1.47.171 Chromium: 109.0.5414.87 (Build ufficiale) (a 64 bit)
- Firefox (Version 109.0 (64 bit))
- Chrome: Version 109.0.5414.74 (Build ufficiale) (a 64 bit)

**Comment by gappc** [comment]
@sseppi should be resolved, please check
