### ISSUE TITLE
As an Open Data Hub manager I want an improved mobile version

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#279]
- [ ] analyse the actual mobile versione
- [ ] collect feedback from the first beta users
- [ ] define a improved mobile version
- [ ] implement the improved mobile version

**Comment by sseppi** [comment]
I post in this comment a possible optimization that I experienced.
I describe the steps I did:

1. access in a Table view
2. open the toolbox
3. input something to search in the Basic Search field
4. click on search
5. close the toolbox by clicking on the x
6. see results

The expected behaviour was to skip the point number 5. So my suggested process would be:

1. access in a Table view
2. open the toolbox
3. input something to search in the Basic Search field
4. click on search
5. the toolbox closes automatically in the onClick event
6. see results

**Comment by sseppi** [comment]
@pkritzinger in your opinion, with the new design you elaborated in the issue #204 do we solve also this issue?

**Comment by pkritzinger** [comment]
@sseppi what do you exactly mean? 

- Which design was implemented when the original comment was created (25th Jan)?
- Which feature of the "new design" do you mean? The latest design refers to the overview of the datasets and not to the tabel view.

**Comment by sseppi** [comment]
@pkritzinger with the last design update the usability also on mobile was improved.

Shall we keep this issue open till the UI/UX testing with real users is done or would it be better to close it and open a new issue based on the feedback of the users?

In any case I would foresee in the testing also that the users tries to use the tool also on mobile.

**Comment by pkritzinger** [comment]
@sseppi I would suggest to:

- Close this issue since we made an improvement.
- I will note in the moderators guide as feedback that we should also foresee mobile usage in the UX-Test.
- Reopen dedicated issues based on the results we find in the test.

**Comment by sseppi** [comment]
@pkritzinger OK, I agree. I close this issue.
