### ISSUE TITLE
Define content for static pages

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#280]
The footer of the start page contains links to some static pages:

- Sitemap
- Legal
- Privacy
- Imprint

We should define the appropriate content before going live.

**Comment by mrabans** [comment]
Proposal:

* Privacy link: https://noi.bz.it/en/privacy-cookie-policy
* Imprint link: https://noi.bz.it/en/impressum
* Legal: hide for now, as there is none neither on the NOI Techpark website nor on the Open Data hub website
* Sitemap: hide for now, as there is none neither on the NOI Techpark website nor on the Open Data hub website

**Comment by gappc** [comment]
@mrabans: I agree that we can remove Legal and Sitemap pages. Regarding your proposal for Privacy / Imprint pages: do you mean to copy / paste the content or to link to the mentioned pages?

@sseppi, @emilylouisesimonis: what's your opinion?

**Comment by ohnewein** [comment]
On January 29, 2023 1:11:58 PM GMT+01:00, gappc ***@***.***> wrote:
>@mrabans: I agree that we can remove Legal and Sitemap pages. Regarding your proposal for Privacy / Imprint pages: do you mean to copy / paste the content or to link to the mentioned pages?
>

I suggest to use links. This ensures the content stays in line with the content on NOI.bz.it. 

Best regards
Patrick

**Comment by sseppi** [comment]
I agree with Patrick, also on the Open Data Hub website we use the same links suggested by Martin.

**Comment by emilylouisesimonis** [comment]
In general, we have not yet done a job of harmonising all footers, so I think things could change. 
But I agree with what Martin & Patrick wrote:
**Privacy**: should direct you to the NOI link: https://noi.bz.it/en/privacy-cookie-policy
**Imprint**: on the opendatahub.com website we have never actually put it there as a link (@sseppi let me know if it needs to be added) bu we have this inscription: NOI AG - Via Volta 13/A, I-39100 Bolzano - VAT No.: 02595720216 - Endowment capital 110.740.000 € - [Privacy](https://noi.bz.it/en/privacy-cookie-policy)

However, in addition, it would be very useful to have a link to the main **opendatahub.com** website

-----

If there were a possibility in the future I would also include links to **"social media"**
I would put the same ones that are in the footer of opendatahub.com (with their corresponding icons):
- https://www.facebook.com/opendatahub/
- https://github.com/noi-techpark/
- https://t.me/OpenDataHub
- https://app.element.io/#/room/#opendatahub:matrix.org

**Comment by gappc** [comment]
@sseppi, @mrabans, @emilylouisesimonis, @ohnewein: I removed to links to Legal and Sitemap and set the links for Privacy and Imprint as suggested by @mrabans.

If you want to discuss additional links to opendatahub.com and "social media" as mentioned by @emilylouisesimonis, I suggest to close this issue and open a dedicated one that focuses on that topic.
