### ISSUE TITLE
As an Open Data Hub manager I want to add link to website and social, to promote them with our community.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#284]
It would be very useful to have a link to the main **opendatahub.com** website

-----

If there were a possibility in the future I would also include links to **"social media"**
I would put the same ones that are in the footer of opendatahub.com (with their corresponding icons):
- https://www.facebook.com/opendatahub/
- https://github.com/noi-techpark/
- https://t.me/OpenDataHub
- https://app.element.io/#/room/#opendatahub:matrix.org
-----

My suggestion is to do something similare as we did in the Open Data Hub Website (See screenshot below), by putting this lnks in the footer of the site.

![Schermata da 2023-01-31 09-26-56](https://user-images.githubusercontent.com/7909989/215708161-0fc4733d-7f93-4557-8b5f-82baf6d5a701.png)

@pkritzinger what do you think?

**Comment by sseppi** [comment]
We need a rework of the entire footer, and we should consider if it has sense to shift this issue together with the review of the navigation.

**Comment by pkritzinger** [comment]
@sseppi lets do this in combination with the navigation. we will try to provide a new proposal for the navigation asap.

**Comment by sseppi** [comment]
@pkritzinger OK I agree to discuss this issue together with the navigation (Issue: #204 ).

For this reason I moved this issue in the Milestone 2.2
