### ISSUE TITLE
As a Open Data Hub manager I want to define a strategy for the domains of each beta version of the Data Browser

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#286]
We need to define a domain strategy for the next beta releases we will do.

In order to take a decision I would like to know your opinion about the following aspect.

Shall we keep online all beta version till we reach a final 2.0 version? In this case for example for the version 2.1-Beta we should create a dedicated pipeline that publish the new version at the following domain:

https://v2-1-beta.databrowser.opendatahub.com

And I would suggest to include in the beta tag the version by writing **V2.1 Beta**

**Comment by sseppi** [comment]
@mrabans , @pkritzinger and @Mazzolintis What is your opinion?

**Comment by mrabans** [comment]
@sseppi This is a policy that can be applied, where parallel developments need different revisions.
I do not see the need of keeping all beta versions online. 

At maximum we can introduce a development version, so we have 3 stages:
* Development version: dev.databrowser.opendatahub.com or alpha.databrowser.opendatahub.com 
* Staging version: v2-beta.databrowser.opendatahub.com 
* Production version: databrowser.opendatahub.com

**Comment by sseppi** [comment]
@mrabans I agree, the only thing I would change is the Development Version. I think we can use the testing environment as the Development one. So the links will be:

* Development version: databrowser.opendatahub.testingmachine.eu
* Staging version: v2-beta.databrowser.opendatahub.com 
* Production version: databrowser.opendatahub.com

In this way we won't need to create new pipelines and maintain a new domain. Moreover in testing we will use the testing databases and so, if we have some problem that stores wrong data in the database, we do not compromise the production environment.

What do you think?

**Comment by sseppi** [comment]
@gappc here you find the logic for the next version for the urls for Development, Staging and prod versions
