### ISSUE TITLE
As an Open Data Hub Data Browser user I want to access a recod by clicking on a raw of the Table View

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#287]
After getting feedback from some beta tester the expected process to access the **Detal View** of a record from the **Table View** is the following:

1. access the Table View of the dataset
2. click on the raw of the record I want to open
3. enter in the Detail View of the selected record

The last column should be used for accessing all other views.

**Comment by sseppi** [comment]
@pkritzinger and @Mazzolintis will think about this feedback we received from the users to understand how to improve the behaviour.

**Comment by pkritzinger** [comment]
@gappc would it be possible to use a long-click for this usecase.
Idea behind: user clicks for a long time on the row, the row fills up with a background and if its fully filled the action (i.e. linking to detail view) is made.

@sseppi what do you think?

**Comment by sseppi** [comment]
@pkritzinger Thank you for the proposal! 

I was trying to think on the user expectation that Patrick told me. He told me that his expectation was that clicking on the raw the main event is "Open the record chosen" and not to edit or do something else. For this reason, in my opinion, the simplest action to do should be the access to the Detail View of a record. So my feedback would be the following:

**Mobile**
- Simple click on the raw: I access to detail view of this recod
- Long click on a single cell: I activate the edit mode of this cell

**Desktop**
- Single click on the raw: I access to detail view of this recod
- Double click on a single cell: I activate the edit mode of this cell

What do you think about my proposal?

**Comment by pkritzinger** [comment]
@sseppi in general the proposal is super, the only problem we face is that there are links within the table view and the option to expand/ collapse information. That's why the single click cannot be used from my point of view. 

LINKS:
![image](https://user-images.githubusercontent.com/92454516/222755512-ae7264ed-44e7-4d52-9df3-c626703348ca.png)

EXPAND: 
![image](https://user-images.githubusercontent.com/92454516/222755783-86be898b-fb9f-4dd1-a798-cae7d2fba419.png)

**Comment by ohnewein** [comment]
Hi all,

my suggestion is to implement the same user experience of Google Spreadsheet. Let's avoid to reinvent the wheel.

We would be better off, if we can tell the user: "It works exactly like Google Drive's Spreadsheet!"

What do you think? Would it be possible?

Patrick

**Comment by gappc** [comment]
@ohnewein I see the advantage of having a Google Spreadsheet like experience, but for the Data Browser there are some obstacles:

- not every column consists of a simple value (string, number, boolean). Some of the columns show complex data, e.g. Webcam data or GPS. The question is, how to edit such complex data in a table
- some datasets have a lot of fields (e.g. ODHActivityPoi has more than 70 fields just in the first level of the data structure). I'm not sure how such a dataset could be visualized in a table in a way that a user is not overwhelmed (maybe with some column filters?)
- the Data Browser concept is (was?) to have a table-like view and some single-record views (e.g. detail view). While it may be possible to use the table for everything, some amount of work would have been done without benefit - except from gained knowledge about the problems and possible solutions

In my opinion, if we want to go the Google Spreadsheet like experience way, the first step would be to find out how it should work in detail.

**Comment by sseppi** [comment]
Hi @ohnewein , hi all,

thank you for the feedback.

> my suggestion is to implement the same user experience of Google Spreadsheet. Let's avoid to reinvent the wheel.

I agree that we do not have to reinvent the wheel. Anyway we have to consider that, Google Spreadsheet does not foresee to have another view to see all details/content of each single record (raw). So we need to consider that we have an action more (access the Edit/Detail) to introduce in the table view.

Looking at the feedback I got, the most important functionality in this view is the access to the Detail/edit view.

> We would be better off, if we can tell the user: "It works exactly like Google Drive's Spreadsheet!"

To take a better decision I had a look on how it works in Google Spreadsheet:

- one click on a cell and becomes editable
  - if it is a link it opens a "popup" with the link and the possibility to open it (see image below)
![Schermata da 2023-03-06 11-24-09](https://user-images.githubusercontent.com/7909989/223087659-952838fc-06b6-42e2-8b0a-56fa11d3a9e0.png)
- two click on a cell and becomes editable
  - if it is a link it opens a "popup" with the link and the possibility to open it (see image below)
![Schermata da 2023-03-06 11-35-38](https://user-images.githubusercontent.com/7909989/223088038-2f5e89ed-4357-403b-a4cc-56b498e19c18.png)

In this case we could use the same behaviour as Google Spreadsheet, but using the one click to open the Detail/Edit view instead the selection of the single cell.

For long content Google spreadsheet has two different use cases:
- the cells adapts automatically its dimension to the content and shows always everything;
- the cell has a fix dimension and the content that has no space is hidden behind other cells (see image below) and the user has to change manually the dimension of the column or row to see the missing content.
![Schermata da 2023-03-06 12-14-12](https://user-images.githubusercontent.com/7909989/223095280-d8e43957-cf55-4e51-96fc-13bc8da59659.png)

For the **more** button, since for the moment the Data Browser user isn't able to change the dimension of columns and raws (feature foreseen in one of the next iterations) we could follow two different approaches:
- we show always the entire content
- we use a logic similar as the one for the links.

I hope that this summary helps all in identifying the solution that best fits our needs.

@pkritzinger what is your opinion?

**Comment by pkritzinger** [comment]
@sseppi in general, the overall idea sounds pretty good, but we should discuss to what extent direct editing within the table view makes sense. From one point of view due to the topics @gappc  mentioned (e.g. complex attributes like GPS data). From the other point of view, the table view was not configured for editing data but rather for showing the most relevant data of a record, i.e. we did not select attributes of a record within the table view based on the need to edit them.

**Comment by sseppi** [comment]
@pkritzinger in this iteration I would keep the Table View only to render data and not extend it to edit data the data. After getting more feedback from the users we will evaluate if there is the need to add Edit Funtionality to the table view and for which data.

Considering that I would ask you to elaborate a proposal on how we could manage the following aspects:
- enter in the Detali/Table view
- how to deal with cells that contains a link
- how to deal with cells with long content

I would keep free the double click/long click in case we need to activate the editing, since it is the standard way other tools activate the edit modality.

**Comment by pkritzinger** [comment]
@sseppi so just to get you correctly: the task remains as it is described in the issue, i.e. "as an Open Data Hub Data Browser user I want to access a record by clicking on a raw of the Table View"?

**Comment by sseppi** [comment]
@pkritzinger Yes, for the editing in table view we will open a dedicated issue in case of need.

**Comment by sseppi** [comment]
@pkritzinger and @Mazzolintis I found maybe another example that could help you in identifying an improved user experience on access the dataset. By using our CRM Dynamics, which has a similar behaviour in the Table that shows all services (in our case the datasets), I noticed that their approach is to let the user click the name of the service to access to its details. See the screenshot below.

![Schermata da 2023-03-22 11-23-35](https://user-images.githubusercontent.com/7909989/226876988-26e19d58-3028-492f-afe8-45c907a9ab7f.png)

So in the case of Dynamics in the example below the behaviour is the following:
- click on Name --> the detail page of the selected service will be open
- click on Customer --> the detail page of the selected customer will be open
- click on Owner --> the detail page of the selected owner will be open

In our case (for the moment) we do not have to open the single details of the related content of a record like Dynamic does with the Customer or Owner for example. So maybe a possible solution could be to let the user open the Detail View of a specific record also by clicking the name of the record.

One related question is also, if we decide so, shall we put always the name as first column?

What do you think?

**Comment by pkritzinger** [comment]
@sseppi thanks for the input, I like the idea.
Unfortunately we still face the problem that we do not exactly know what the record name is - or stated alternatively: we would have to define in the configuration or the Metadata-API what the name is. This is kind of the same problem as we have in issue #270 

If we find a solution to the above stated topic, I am fine with it :)

Alternative solution:
- Clicking on raw opens Detail View (except for cells with links or expandable options - like ODH tags. In that case the link is opened or the options are expanded)
- Long click on a cell allows user to save respective content in clipboard

**Comment by gappc** [comment]
@pkritzinger unfortunately the alternative solution is complicated to implement. First, we don't know without further configuration which cells should be clickable and which not, so the problem of additional configuration overhead remains (even more in case other companies provide their cell components). Second, the implementation of long-click with selection of data is non-trivial. In effect, we would have to implement large parts of what browsers provide out of the box, which is almost never a good idea.

I see several other options:

- as discussed, use MetaData API to declare which field should be used as dataset name and show them as first column and make it clickable -> we need MetaData API integreation also for #270. **Everyone please note** that also this solution brings new problems (e.g. what should we do in case a dataset has no config in MetaData API? What should we do for the generated config?)
- move the buttons to the left, such that they are more prominent
- use text instead of buttons, e.g. "detail", "edit", ...

Are there other ideas?

**Comment by pkritzinger** [comment]
Thanks for the input @gappc 
Will continue discussing with @Mazzolintis and come up with other suggestions.

**Comment by sseppi** [comment]
Hi all,

thank you for the inpunt.
For the moment, that we do not have everything ready for an optimal solution, would it be an option to make always the first column clickable? I had a look and in the actual configuration we have always as first column one of the following data:

- Image
- Title
- ID

This could be applied also to the no config, where we have always the ID as first column (If I'm not wrong).

**Comment by gappc** [comment]
@sseppi interesting suggestion, if its OK that the Title / ID can not be selected / copied anymore, then we can implement it.

Another solution that came to my mind would be to put e.g. some background color on the row that contains the Detail- / Edit- / Raw-Buttons, such that it is more clear to the user that this is something special.

**Comment by sseppi** [comment]
OK, 
let see what @pkritzinger and @Mazzolintis propose on top of all the inputs we provided.

**Comment by pkritzinger** [comment]
thanks for all the inputs @sseppi @gappc 
As mentioned, we will provide different options.
One thing we need to clearly differentiate:
is clicking on a row desired because it is not clear how to access detail, edit or raw view or is it due to efficiency of usage?

I would assume it is due to the latter, but we can also improve comprehensibility for the current access points to detail, edit and raw view.

**Comment by pkritzinger** [comment]
@sseppi @gappc 
Updated design can be found here.
https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?node-id=174%3A2170&t=uzGHjlYdtNKLXSl1-1

**Comment by sseppi** [comment]
@pkritzinger as agreed with Patrick in yesterday's meeting I ask you to update the design accordingly to the decision we took.

The agreed behaviour of the table should be the following:

* one click on each cell of a row --> select the row
* double click on each cell of a row --> access the detail view of the record displayed in the raw

This probably means that we have to show always the entire content in the cells and disable for the moment the ``show more`` button in case of long lists or texts?

For the cells with link what do you think it would be better: just treat it like all other cells, let the link dominate (One click --> open link instead selecting the raw) or allow to open the link only by a combination (windows like: CTRL + one click)?

Once we answered this two quetions, I think we are ready to move the issue in the ToDo lane.

**Comment by pkritzinger** [comment]
@sseppi find the visualization of how a clicked row should look like here:
https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?type=design&node-id=574%3A7410&t=YJzUEKIvejksK2bS-1

Regarding the open questions: I would always let the link dominate, otherwise clicking behavior of links in the table view would be different from all other links in the databrowser. 
Why do you think we need to remove the show more button from the table view? Couldn't we handle that like a link?

**Comment by sseppi** [comment]
@pkritzinger thank you for the explanation.

I agree with you, let try to start with the links dominant. Regarding the ``Show more`` button, if it is not too complex to handle on the development side, I would go on with your proposal.

@gappc is it fine for you? can we move this issue in the ToDo lane?

**Comment by gappc** [comment]
@sseppi @pkritzinger I think we can move it to the ToDo lane (please prioritize), I just need to know if we also should change the Quick-/Detail-/Edit-/Raw button on the right side, like shown in the linked design

**Comment by pkritzinger** [comment]
@gappc good point - sorry, forgot to mention that. from my pov it would be great if we changed them, @sseppi what do you think?

**Comment by sseppi** [comment]
> @gappc good point - sorry, forgot to mention that. from my pov it would be great if we changed them, @sseppi what do you think?

@gappc I agree with what Paul said. I will put the issue in the ToDo lane with the right priority

**Comment by gappc** [comment]
@ohnewein @sseppi @mrabans @pkritzinger @Mazzolintis implementaed as of 84b185ed6455a484360aef7ce9d8cd59e3bfa800

You can take a look at it e.g. here: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/ODHActivityPoi

Please let me know what you think about the implementation

**Comment by sseppi** [comment]
@gappc nice! I like it and also @ohnewein likes!

Shall we move the issue in the review lane, test it more heavily and, if everithing fine, close the issue?

**Comment by pkritzinger** [comment]
@gappc one thing I came across: when I click on the link in the table view (Screenshot: https://prnt.sc/iZU-PB-ULv03) the following link is opened, leading me to an error-message of the tool: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/www.mercatino-natale.it

Expected behavior: only the link itself should be opened in a new tab.

**Comment by pkritzinger** [comment]
@gappc oh god, did I really click on the only record without http/s? 🤣

Got it, so no to-do from my pov.

**Comment by ohnewein** [comment]
The question for me is: 

Should the Data Browser create a sort of isolation here? Should every link be automatically encapsulated into an https is not yet specified and always open in a new tab ( target="_blank )?

I think that would be what the user is expecting. A consistent behavior.

**Comment by pkritzinger** [comment]
@ohnewein see your point.
My only thought was whether it's the databrowsers job to "manipulate" data or whether it should only visualize them. 

But its definitely up to you to decide 😄

**Comment by sseppi** [comment]
@ohnewein @pkritzinger 

In my point of view 
- it is a good idea to open external links in a new tab ( target="_blank" )
- I wouldn't automatically encapsulated into an https, but maybe we could create a dedicated error message? I think that the Data Browser could be also a tool that allows our Data Provider to discover and improve data quality issues like this one that has to be fixed directly on the source.

What do you think?

**Comment by gappc** [comment]
@sseppi the links already open in a new tab

**Comment by pkritzinger** [comment]
@sseppi I like @gappc's suggestion to show incorrect links as text only.
If we want to show the link and an error message we could use the already existing behavior and optimize it:
- Remove crossed out content
- Change wording of error message (to be defined)
- Integrate mailto:help@opendatahub.com in error-message to provide feedback for data quality

![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/92454516/39aacafd-9e43-4942-b8bd-d3de89b42246)

**Comment by ohnewein** [comment]
I would be careful with error messages. They usually break the user flow and should be only used for exceptions when something really unexpected happens and the tool cannot handle the situation. In this case it is all predictable and the tool has to know how to handle the situation.

I also like the suggestion by @gappc  to render malformed URIs as simple text. 

Let's try that.

**Comment by sseppi** [comment]
@pkritzinger @ohnewein @gappc thank you for the feedback.

So let go on and implement the solution as proposed by @gappc

**Comment by gappc** [comment]
@ohnewein @sseppi @pkritzinger the proposed solution was implemented as of 19f0426641227b0d0fb942da7143dcef2f5a035b

You can take a look at it e.g. here: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/ODHActivityPoi

If the solution is ok and all of the other requirements of this issue are satisfied, then please close this issue.

**Comment by sseppi** [comment]
Hi all,

I tested and it seems to work fine. What I like, is that a data provider with two little steps (one sorting and a filter) has an overview of a lot of wrong links that has to be improved:

https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/ODHActivityPoi?rawsort=-ContactInfos.en.Url&rawfilter=and(isnotnull(ContactInfos.en.Url))

Thank you all!
Stefano

**Comment by pkritzinger** [comment]
@sseppi this is pretty cool 🚀

**Comment by sseppi** [comment]
Since this issue has been tested by our team in the last weeks, and nobody found bugs, I colse this issue.
