### ISSUE TITLE
As an Open Data Hub Data Browser visitor I want to see more details by clicking on the **More Info** button

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#288]
In the actual version if th user clicks on the **More info** button it doesn't receives any feedback.

The proposal is to show the following information:

- Dataset name
- Dataset description
- Availability of data
- Number of records

All data shown must come from the Metadata API: https://tourism.api.opendatahub.bz.it/v1/metadata

**Comment by pkritzinger** [comment]
See update here:
https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?node-id=8%3A855&t=kZTFyhuvfbX1sTJ8-1

**Comment by sseppi** [comment]
@pkritzinger the idea is generally fine for me. The only thing I would change is the name of the "More information" button since it seems a duplicate of the button "More info" above. I would suggest to change it into "Dataset Detail" or something similar.

What do you think?

**Comment by pkritzinger** [comment]
@sseppi good input, thanks - design is updated.

**Comment by gappc** [comment]
@sseppi, @mrabans, @pkritzinger: done as of 57e5cb09988dfa176fe30a38a8a57be3c1b7378c, you can take a look here: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Article?source=noi

If it's ok, please close the issue

**Comment by pkritzinger** [comment]
@gappc cool - can be closed from my point of view!

**Comment by sseppi** [comment]
Hi all, the issue can be closed also from my point of view.
