### ISSUE TITLE
There are two Metadata APIs

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#290]
At the moment, there seem to be two different Metadata API endpoints, for the TEST environment, those are:

- https://api.tourism.testingmachine.eu/v1/MetaData
- https://api.tourism.testingmachine.eu/v1/Metadata (please note the lowercase "data")

@RudiThoeni: which one is the one to use? I suspect it is `Metadata` as mentioned in https://github.com/noi-techpark/it.bz.opendatahub.databrowser/issues/184#issuecomment-1326484332. If that is correct, could you remove the other endpoint to avoid misunderstandings?

**Comment by RudiThoeni** [comment]
you are right there was some mixed routes (however the .net core framework routes are not case sensitive),  i fixed, let's use
https://api.tourism.testingmachine.eu/v1/MetaData

I inserted everywhere this routes,

**Comment by gappc** [comment]
Ok, I'll update #184 accordingly
