### ISSUE TITLE
As an Open data Hub Manager I want a Graphic Style guideline, to reduce the entry barrier for new Developers.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#295]

**Comment by pkritzinger** [comment]
https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?type=design&node-id=9%3A1054&t=9jPzmCAZIctsFMf8-1

**Comment by sseppi** [comment]
@sseppi and @mrabans will review the link in the next sprint.

**Comment by sseppi** [comment]
@pkritzinger I noticed that the ``Testing`` tag is missing... Can you please create one as you did for the ``Beta`` one?
