### ISSUE TITLE
As a Open Data Hub Data Browser user I want a new icon for missing images, to better understand that there are no images.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#300]
I share here two examples of possible placeholder icons/image that can be used as reference in the definition of the new icon.

![Image](https://user-images.githubusercontent.com/7909989/220323391-dde239c6-956e-4114-873d-8203d4b03957.png)
![Image](https://user-images.githubusercontent.com/7909989/220323392-4b391247-219e-42d3-b195-c313a08a5a13.png)

**Comment by pkritzinger** [comment]
There's not enough space for the text since the space for the image is too small.
We've changed the icon, looking forward to your feedback.
@sseppi


![Image](https://user-images.githubusercontent.com/92454516/222708956-af02d3f2-6a8f-4ba2-b1d0-085657cf8465.png)

**Comment by sseppi** [comment]
@pkritzinger i assume that the problem is for small devices. Can you please share a screenshot of the entire Data Browser or the link to the Figma file where I can see the entire Table View with the icon? It would be really helpful to understand if the direction is the right one.

@mrabans what do you think?

**Comment by mrabans** [comment]
@sseppi @pkritzinger a red cross in general indicates there is something wrong or someone has to stop. This is a harsh symbol for showing that there no image. We might use this placeholder in cases where there cannot be any image because it's maybe a sensor and there is an icon attribute. 

To have a more general icon (outside of the tourism domain) I'd remove the red cross and work with black/white/grey.

**Comment by sseppi** [comment]
@pkritzinger I had a look to the icons with part of the team and the most liked icon to use as placeholder is the fourth one.

@mrabans what is your opinion?

**Comment by mrabans** [comment]
@pkritzinger @sseppi same. Looking at it in two different occasions the fourth is my favorite

**Comment by gappc** [comment]
I also like #4 but is it clear from the placeholder that an image is missing? Anyway, after we have a final decision, @pkritzinger, @Mazzolintis: please provide a way to export the icon as SVG, like for all the icons before

**Comment by sseppi** [comment]
I shared the Figma internally and nearly all people prefers the 4th one. 
So I would say let go on with the fourth one.

**Comment by pkritzinger** [comment]
![placeholder-odh-databrowser](https://user-images.githubusercontent.com/92454516/225652039-97e57614-8871-45d2-8dc1-91d05c807361.svg)

@gappc find SVG here. Are you not able to export the files from Figma? Pls. let me know, in case we should have a look at it together.

**Comment by pkritzinger** [comment]
@gappc ok, lets discuss next time in the meeting.

**Comment by gappc** [comment]
@sseppi, @mrabans, @pkritzinger: done as of a59758724dd5c7d5f9b4a62001618bbea8d40d24, you can take a look here: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/ODHActivityPoi.

If it's ok, please close the issue

**Comment by pkritzinger** [comment]
can be closed from my point of view @sseppi

**Comment by sseppi** [comment]
The issue can be closed also from my point of view.
