### ISSUE TITLE
As a databrowser visitor i want there to be consistency in the obligatory fields symbols 

### ISSUE THREAD

**Issue by d3liaa** [noi-techpark/it.bz.opendatahub.databrowser#303]
The presence of an obligatory field in the edit view is made aware to the usare with an * in the section menu, but within said section the obligatory field is marked with a red dot. I would like to be one or the other.

There is also a bug in mobile mode: The red dot is not visible and it is not clear which field is obligatory.

I would also like to suggest that the tool button should always be visible/ open to have immediately visible the leggend that says what the * stands for as it is not immediately clear in my opinion.

**Comment by sseppi** [comment]
@pkritzinger and @Mazzolintis can you please provide us a feedback on which is the best way to go, so that we can then implement the right solution?

**Comment by gappc** [comment]
@sseppi we (@pkritzinger and @d3liaa) discussed this topic yesterday, the proposal of Paul was to add the "*" behind the title of oligatory (=requred) fields. The red dot will be removed.

If this is ok with everyone, I'll implement the fix.

**Comment by sseppi** [comment]
OK, fine for me.

**Comment by gappc** [comment]
@d3liaa, @sseppi: obligatory fields are now shown with "*" behind them, e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/detail/tourism/v1/Accommodation/5CEA544EE34639034F07B79D4AEEB603_REDUCED

@sseppi: Delia mentioned in this issue that in her opinion the toolbox in the EditView should be open by default. At the moment, the toolbox is configured as follow:

- TableView: collapsed by default, it is possible to open / close it with the appropriate button
- EditView: collapsed by default, it is possible to open / close it with the appropriate button
- DetailView: open by default, it is  NOT possible to open / close it
- RawView: open by default, it is  NOT possible to open / close it
- QuickView: unknown

Should we change that behavior? If so, should we open a dedicated issue to discuss how it should work?

**Comment by sseppi** [comment]
@gappc  Since I see the feedback of @d3liaa as the feedback from a real user, who sees the Data Browser nearly from the first time I would go for trying the open toolbosx per default in the EditView.

**Comment by gappc** [comment]
@pkritzinger, @sseppi: yes we can open the toolbox by default in edit view. Please be aware that it is **NOT** possible to open / close the toolbox in DetailView and RawView at the moment.

Do you want to have this same behavior for the EditView, or should we allow the toolbox in Detail-, Raw- and EditView to be closed / opened?

**Comment by pkritzinger** [comment]
@gappc from my point of view it would be elegant to allow the user to close the toolbox. this can be especially helpful in case of small laptop screens to assure that there is enough width for content.

@sseppi do you agree?

**Comment by sseppi** [comment]
@gappc @pkritzinger fine for me the last proposal of Paul

**Comment by gappc** [comment]
@pkritzinger, @sseppi: I see it the same way. I let you know when the changes are ready to be reviewed.

**Comment by pkritzinger** [comment]
@gappc nice, thanks, issue can be closed from my point of view.
