### ISSUE TITLE
Error loading data in dataset weather

### ISSUE THREAD

**Issue by d3liaa** [noi-techpark/it.bz.opendatahub.databrowser#308]
I was checking the different dataset and for the current weather only the table view works and all the others give this error:
Error while loading data
`AxiosError: Request failed with status code 500 ({"error":"Unexpected character encountered while parsing value: Y. Path '', line 0, position 0."}))`
It happens also in the databrowser in testingmachine here is the link: 
https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/Weather/80698
And also when invoked:
https://api.tourism.testingmachine.eu/v1/Weather/80698

**Comment by gappc** [comment]
@RudiThoeni: could you please take a look at this problem? It seems related to the backend.

**Comment by RudiThoeni** [comment]
fixed ;)

**Comment by sseppi** [comment]
> fixed ;)

Thank you Rudi!
