### ISSUE TITLE
As an Open Data Hub manager I want to see the field "Published on" in the Configured View, to allow the user to see and configure where the data are used.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#313]
On the Open Data Hub API has been added a new field `PublishedOn` that has to be configured in all views. The field shows a list of known consumer tools that is interested in the record. In future there will be a API call that returns a list of all consumer tools already present in the DB.

My proposal would be to reuse the same design we have for the tags and add a **Published on** section. The user accordingly to the rights he will have will have the possibility to:

- only see the list of consumers tools;
- add a new consumer tool choosing only from the list of existing consumers tools;
- add a new consumer tool.

**Comment by sseppi** [comment]
As agreed during the meeting in this iteration we will reuse the "tag component" and offer to the user onli the following funtionalities:

- only see the list of consumers tools;
- add a new consumer tool choosing only from the list of existing consumers tools;

In this iteration the list of publishers will be hardcoded in the configuration. 
@gappc where will you input the list of publishers? We will probaly need to change it while we are waiting the second version of the component.

The list of publishers we have at the moment is the following:

- https://www.suedtirol.info/
- idm-marketplace
- noi-communityapp
- https://today.noi.bz/
- https://noi.bz.it/

In future the API will be extended with the following functionalities:
- publish the list of all publishers
- possibilitỳ to edit the list of publishers

Once this new features of the API will be developed the TAG component will be extended offering the possibility to configure:
- the possibility to add new tags
- the API link to edit the tags

Two dedicated issues will be created on this topic.

**Comment by gappc** [comment]
@sseppi we put the list of publishers into the embedded configuration and reuse that one everywhere we need it.

Looking at the provided list there are three entries that are URLs. Do we need the URLs or is it enough to have appropriate text value, e.g.

- suedtirol.info
- idm-marketplace
- noi-communityapp
- today.noi.bz
- noi.bz.it

**Comment by sseppi** [comment]
> @sseppi we put the list of publishers into the embedded configuration and reuse that one everywhere we need it.

Since it is a temporary solution, fine for me.
 
> Looking at the provided list there are three entries that are URLs. Do we need the URLs or is it enough to have appropriate text value, e.g.
> 
>     * suedtirol.info
>     * idm-marketplace
>     * noi-communityapp
>     * today.noi.bz
>     * noi.bz.it

@RudiThoeni what is your opinion about that?

**Comment by pkritzinger** [comment]
@sseppi @gappc I shortly sneak in here. 
From my point of view it would make sense to add the link to the consumer so that users can have a look at the consumer tool and see how data was implemented. On the other hand: would that mean that the edit-feature gets more complex and users need to insert name and link per consumer in case?

**Comment by RudiThoeni** [comment]
@gappc , @sseppi  Fine for me if we switch to keys only....... 
@pkritzinger we can save the url as info in the publishers list.... so it will be visible there

**Comment by sseppi** [comment]
@pkritzinger the only one thing to consider is that not always we will have a link to the tool which implements the data

**Comment by RudiThoeni** [comment]
ok here a full list of all publishers

`
suedtirol.info
idm-marketplace
noi-communityapp
today.noi.bz.it
noi.bz.it
suedtirolwein.com
centro-trevi.trevilab
centro-trevi.drin
`

**Comment by pkritzinger** [comment]
See user interface design here:
https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?node-id=68%3A2374&t=kZTFyhuvfbX1sTJ8-1

**Comment by sseppi** [comment]
The solution seems to be fine form me, let discuss it with Christian the next meeting.

**Comment by gappc** [comment]
I'm not sure if we have a link, at least the new `Publisher` endpoint doesn't provide any link (see https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Publisher).

Regarding the "Add new" functionality: we need to discuss that in more detail in the next meeting.

**Comment by RudiThoeni** [comment]
i can add a url for each publisher ......

**Comment by sseppi** [comment]
Hi all,

@gappc you're right, this morning I forgot to add this comment.
@RudiThoeni I don't think we need a url since I see the publisher as a tag that says where the data is consumed. And not always it will be a website.

I would propose to remove from the table the column link. Keep it easy, so we can reuse 1 to 1 the Tag component by adding the feature that allows to configure the possibility to add new publishers/tags.

**Comment by pkritzinger** [comment]
@gappc @sseppi @RudiThoeni 
removing the link makes editing and consuming data much easier. 
However: we do not cover this usecase we agreed upon:

> From my point of view it would make sense to add the link to the consumer so that users can have a look at the consumer tool and see how data was implemented.

**Comment by RudiThoeni** [comment]
ok i added a property "PublisherUrl" where an optional consumer tool can be inserted

**Comment by gappc** [comment]
@sseppi we need a decision: should we have the link or not?

**Comment by sseppi** [comment]
I talked with @RudiThoeni and finlly we decided to add also the link.

@gappc Since the link has been already added by Rudi, I would implement the solution as proposed by Paul.

**Comment by gappc** [comment]
@sseppi a first version of the published-on component is implemented, but yet not merged (see PR #326). Please note, that it does not support add-new functionality yet (see #318). Should I merge it?

**Comment by sseppi** [comment]
@RudiThoeni What do you think, for the moment can we merge it and then update the component accordingly with the resual of the issues: #318 and #316 ?

**Comment by RudiThoeni** [comment]
yes ok for me

**Comment by sseppi** [comment]
@gappc so we can proceed with the merge of the PR #326

**Comment by gappc** [comment]
@sseppi @RudiThoeni: merge done as of 6f06ec6d453af1d09921ee96d22d6e0732313982. You can take a look at the result e.g. here:
- Detail View: https://databrowser.opendatahub.testingmachine.eu/dataset/detail/tourism/v1/Accommodation/5CEA544EE34639034F07B79D4AEEB603
- Edit View: https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/Accommodation/5CEA544EE34639034F07B79D4AEEB603

If it's OK, please close this issue.

**Comment by sseppi** [comment]
Fine for  me, if @RudiThoeni agrees we can close it.

**Comment by sseppi** [comment]
@gappc just as reminder I post here below the screenshot of the problem we discovered todan during the Sprint Meeting.

![Image](https://user-images.githubusercontent.com/7909989/229757051-465d444e-3bf7-431f-8e23-3b6bed440de1.png)

**Comment by gappc** [comment]
@sseppi creating a new publisher works, should we close this ticket?

**Comment by sseppi** [comment]
Yes, I coles it and in case of need we will open a new one on top of the users' feedback.
