### ISSUE TITLE
As an Open Data Hub manager I want that the Data Browser is able to get some configuration (e.g. readonly) from Open API, to reduce the effort to manually configure the single Data Sets.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#315]
**Warning:** Once we will take the information read only from the open API the Edit Web Components should be implemented in order to keep the records not marked as read only per default.

**Comment by sseppi** [comment]
**WARNIG** before implementing this issue we need to consider that we should implement a solution that fits also the mobilty API needs

**Comment by sseppi** [comment]
@gappc has this issue been implemented within the issue #423 ?

**Comment by gappc** [comment]
@sseppi the retrieval and merge of the data has been implemented in #423, the visualization is still open

**Comment by gappc** [comment]
@sseppi is this issue still relevant?

**Comment by sseppi** [comment]
Deprecation information and mandatory fields are now retrieved from the OpenAPI.

If so, I think we can close this issue and discuss possible improvements in a new dedicated issue.

@mrabans do you agree?
