### ISSUE TITLE
As an Open Data Hub Data Browser developer I want an API that allows me to get/modify/add all publishers to automatically populate the "published on" component

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#317]
To allow the use a standard TAG component to render and modify the "Published on" information in the data browser we need to extend the APIs with the following functionality:
- [x] possibility to retrieve all existing publishers
- [x] CRUD functionality for the publisher 

deadline: 15 May 2023

**Comment by sseppi** [comment]
@RudiThoeni : do you see potential risk in giving the possibility to modify and delete existing publishers?

**Comment by RudiThoeni** [comment]
the risk is always there but i think we will give the rights of publisher management only to certain people....
But i think we can add some restrictions maybe to not let change the "id/key" of any publisher because here the problem  is more about the documentDB Design of the Database....... when a key is changed all assigned keys on any objects will become orphaned....

**Comment by sseppi** [comment]
@RudiThoeni thank you for sharing your opinion.

So fine for me to proceed as you proposed.

**Comment by gappc** [comment]
@RudiThoeni as far as I understand, the API exists (see generated view in Data Browser here: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Publisher). Is that correct?

@sseppi if the API exists, should we define an embedded view (aka file in git) for the Data Browser such that it can be edited through the Data Browser (please note: at the moment, generated views don't support editing)?

**Comment by sseppi** [comment]
@gappc yes the API has been implemented by Rudi and updated with CRUD functionality.

If it is not a big effort, you can configure also the Edit view for this Dataset. In the issue #318 we should then focus on how simplify the process of adding a new TAG/publisher in general.

**Comment by gappc** [comment]
@sseppi it's not a big effort, I'll put it on my TODO list and let you know when it's done

**Comment by gappc** [comment]
@sseppi @RudiThoeni : config is done as of 92b8241bcea76ea834c2893d6651fe6248cd5a91. You can take a look at it here:

- Table View: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Publisher
- Detail View: https://databrowser.opendatahub.testingmachine.eu/dataset/detail/tourism/v1/Publisher/centro-trevi.drin
- Edit VIew: https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/Publisher/centro-trevi.drin

Please take a look at it and close this issue if it's OK.

**Comment by gappc** [comment]
@sseppi can we close this issue?
