### ISSUE TITLE
Remove lerna

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#321]
At the moment we use [lerna](https://lerna.js.org/) to handle the mono repository, but in reality it is not useful for the project in its current state and only a source of confusion and problems. I'd opt to remove lerna and the base `package.json` and `package-lock.json` files for simplification. At the same time, the docs must be updated.

@sseppi, @mrabans, @MatteoBiasi: what is your opinion?

**Comment by mrabans** [comment]
@gappc yes, i agree. It is a level of complexity we should avoid.

**Comment by MatteoBiasi** [comment]
I agree too!

**Comment by sseppi** [comment]
I agree too.

@gappc shall we put this iteration in the next iteration?

**Comment by gappc** [comment]
@sseppi yes, but lets first take a look at the current planning in tomorrows meeting.

**Comment by sseppi** [comment]
@gappc OK, I've put the issue in the backlog. Tomorrow we will decide which in which Milestone we will introduce this issue

**Comment by gappc** [comment]
@sseppi lerna was removed as of b84c3d2743cffd7a5048b3b2df9186ae288c6c98. I think we can close this issue.

**Comment by sseppi** [comment]
@gappc thank you!
