### ISSUE TITLE
If an user tries to open the configured view of a not configured dataset, the data aren't displayed and it appears an error message.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#341]
If the user tries to access directly a `Embedded View` of a not configured dataset (e.g. Area), the dats arend displayed and it apperars the following error message:

"
**Error!**
No view configuration found
"

See the following link for an example:
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Area

In this case I would suggest to leave the error message, but also open the `Generated view` below. In this way the user will know that the data are there, but there is still no configuration for it.

**Comment by gappc** [comment]
@sseppi this should not happen anymore. If you click on the link you provided, the generated config is shown. Please check and close this issue if everything is ok.
