### ISSUE TITLE
File line endings: Improve project compatibility with Windows

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#345]
Line endings in Windows OS are different than those in *ix OS. This is a problem for GIT commits. 

One solution seems to be to set the line endings in `.gitattribute` but we have to check if this creates problems before we can use such settings.

**Comment by henri-egger** [comment]
@gappc
Summarizing PR #390:
- Just adding a Prettier linting rule to ignore line endings would solve the problem for now but could lead to problems later.
- Some contributors working on Windows might already have found a local solution, would need to reach out to them.
- Adding a `.gitattributes` file containing `* text=auto eol=lf` to the project root seems to be best option, the official Prettier docs even mention this solution. However, this is intended to be implemented when creating a new project. When implementing it in an existing repository it seems that the file has to be on the branch which will be referenced in HEAD upon cloning, which is the reason it wasn't working for me the first time. This means that the file should take effect when cloning normally once put into the development branch. Right now this is testable with `git clone <origin> --branch windows-linting`.
  You might just want to create the file via Github if this solution is ok for you, or i could make a new branch without the accidental git-hook commits and open a PR.

**Comment by gappc** [comment]
@henri-egger very nice overview, thank you :100: 

Please go on and create a PR with the suggested changes.
