### ISSUE TITLE
Configure the Age from Age to fields in the new Data Browser

### ISSUE THREAD

**Issue by cdercoli** [noi-techpark/it.bz.opendatahub.databrowser#357]
Configure the Age from Age to fields in the new Data Browser in the Event Short dataset. 
Rudi added the following attributes in the EventShort endpoint: AgeFrom, AgeTo. They are expressed as an array so it's possible to insert more Age Ranges. 

"TypicalAgeRange": [
    {
      "AgeTo": 2,
      "AgeFrom": 1
    }
  ],

It is available in the GUI on the Tagging Tab as visible from screenshot: 
![image](https://user-images.githubusercontent.com/105744782/233401956-70ede2b0-2639-4041-81d8-6411307331a9.png)

**Comment by gappc** [comment]
@cdercoli thank you to add this issue. Could you please provide some more details as it is not clear to me what you mean?

**Comment by sseppi** [comment]
@cdercoli can you please add the information that Rudi shared in the Request Tracker (including the screenshots) issue so also @pkritzinger and @Mazzolintis can help us in identifying the right graphic component to be used.

@gappc this is a new feature that, or request of a client of us, has been added to the EventShort dataset.

**Comment by gappc** [comment]
@sseppi Milestone 2.2 is already ongoing.

As stated already some times, I think it is not a good practice to continue to pull issues into an already running Milestone because the result is that other tasks will be postponed and the whole project planning will become more and more obsolete.

Please don't get me wrong: if we really have to put the feature into 2.2 than that's fine with me, but I think we must understand the results of such decisions and the implications they bring.

**Comment by sseppi** [comment]
@gappc i got your point and let discuss it in the refinement meeting and define there the priorities... Unfortunately we have to deal with this unforeseen developments to fit the needs of our beta testers.

**Comment by mrabans** [comment]
Hi

As discussed with Martin on the Meeting Today i changed the TypicalAgeRange from an Array to a Single Object

example

  "TypicalAgeRange": {
    "AgeTo": 99,
    "AgeFrom": 5
  },

visible here:

https://api.tourism.testingmachine.eu/v1/EventShort/ce371092-296f-47a4-b7ee-73510a1cf646

 

cheers

Rudi

**Comment by gappc** [comment]
@sseppi do you have an update on this issue? Should we add it to the milestone or further postpone it?

**Comment by sseppi** [comment]
@gappc This functionality has been already implemented by @cdercoli . I think we forgot to put this issue in the kanban and in the To Review lane.

https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/EventShort/e98699d1-0ab0-4197-aa74-a9226d6e821c?source=noi#event-details

 tested and it seems to work fine, if you don't see any technical problem, I think we can close the issue.
Do you agree?

**Comment by gappc** [comment]
@sseppi looks good to me, in my opinion you can close the issue. @cdercoli nice work, thank you :+1:
