### ISSUE TITLE
Husky does not prevent code with warnings from being committed

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#371]
@gappc fixed. Strange that husky let me do the commit with those two warnings.

_Originally posted by @MatteoBiasi in https://github.com/noi-techpark/it.bz.opendatahub.databrowser/issues/366#issuecomment-1547423165_

**Comment by sseppi** [comment]
@gappc verifies if the proble is still there. If not, he will close the issue.

**Comment by gappc** [comment]
@sseppi PR #562 solves this issue
