### ISSUE TITLE
Improve data fetch animation

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#373]
It should be visible to a user when data for the different views is loaded.

Data loading happens:
- on (Table/Detail/Edit/Raw) view load
- on filter change
- on sort

A design idea was delivered by studiohug, it should look like shown below:

![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/5732768/cc187f34-f927-4485-9a3d-888efe019dde)

**Comment by sseppi** [comment]
As agreed yesterday, I close this issue since everything works fine.
