### ISSUE TITLE
Bad Overlay for Sorting and Filtering on Safari

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#377]
I created an issue that can be used as template to create a bug report.

- **Device**: Mobile - iPhone 11
- **Operating System:** iOS 16.4.1
- **Browser:** Safari
- **Problem Description:**
  - If i click on "Add filter..."-Button, the Overlay for adding a filter is opened but the sort/filter-menu is still visible. Expected behavior: after clicking on "Add filter"-Button the the menu should be closed. https://prnt.sc/czW4KF-yoMIc
  - When I scroll the table and open the menu, it is sometimes partly out of the viewport https://prnt.sc/6HE7Nn7Ex8Lh 
- **Expected behaviour:**
Expected behavior (suggestion): Menu is horizontally centered to arrow?
- **Screenshots:**
  - https://prnt.sc/czW4KF-yoMIc
  - https://prnt.sc/6HE7Nn7Ex8Lh

**Comment by gappc** [comment]
@sseppi @pkritzinger fixed as of f28bb823b6a121ac742807d1354a068e7370098e

You can take a look at it e.g. on https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation

If it is ok, please close the issue.

**Comment by sseppi** [comment]
@gappc thank you for the fix!

@pkritzinger does work it fine on Safari on iPhone now?

**Comment by pkritzinger** [comment]
@sseppi yes, is working fine now - thanks @gappc

**Comment by sseppi** [comment]
Super, so I close this issue. 
Also Emily confirms me that the issue seem to be solved.
