### ISSUE TITLE
As an Open Data Hub Data Browser mobile user i want to have the possibility to reset all Filters applied to my table view.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#378]
During the sprint meeting of the 16.05.2023 it has been discussed the positioning of the "Reaset all filters"  button.

The decision that has been taken are the following:
- the information "Fiters active" will be put at the top of the table view below the "Embedded view" label;
- the "Reset" button will be at the seme legen of the "Filters Active" info text
- the active filter information raw will appear only if filers are active in the table view
- the background of the active filter information raw will be darker to underline is something new

**Comment by pkritzinger** [comment]
@sseppi @gappc  - check this out:
https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?type=design&node-id=398%3A5508&t=9jPzmCAZIctsFMf8-1

What do you think?

**Comment by sseppi** [comment]
@pkritzinger fine for me!

If @gappc and @mrabans agree, we can move this issue in the ToDo lane

**Comment by gappc** [comment]
@sseppi @mrabans @pkritzinger implemented as of a3abcfc2f79b7b82099ede00dab02e358d53a613

You can take a look at it e.g. here (on mobile): https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation?rawfilter=and(eq(AccoDetail.en.Name,%2718%27))

If it's ok, please close this issue and the related issue #72

**Comment by sseppi** [comment]
@gappc It works fine also on Firefox on Android.
