### ISSUE TITLE
Filtering error: The filter includes works like equal to

### ISSUE THREAD

**Issue by d3liaa** [noi-techpark/it.bz.opendatahub.databrowser#380]
Device: Desktop
Operating System: Windows 11
Browser: Chrome
Problem Description:
The filter `includes `works like `equal to `. 
When i inserted a fraction of the title in the search (Title includes "Sonvigo") in the dataset district the search had no result when it should have shown the Sonvigo/Aberstückl district. It showed th result only after i inserted the whole title, like in an equal to search.
Screenshots:
![ss_filter_includes](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/101118017/918b30c4-a440-45fa-8b2b-038d18c2431d)
![ss_filter_includes_2](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/101118017/02aa55bb-fa96-44aa-a567-38ff0ffe1238)

**Comment by sseppi** [comment]
Hi @d3liaa ,

thank you for the information.
The include operator is not like a contains operator. I try to explain you the differences here below:

The include operator checks if the element is included a certain value. Typically is used to verify if an array or list contains a certain value (eg. rawfilter=in(PublishedOn,'noi.bz.it') is the filter that returs all events that icludes in publishOn list the value "noi.bz.it").

Unfortunately at the moment we do not have a contains filter that checks if a certain sub-string is included in a string.

How would you suggest to solve this misunderstanding between the include and contains operator? Shall we document it in the documentation of the filters you are preparing?

Best
Stefano

**Comment by d3liaa** [comment]
Hi @sseppi ,
Thank you for the explanation! For now, i put the difference in the documentation!
A small idea:
If possible i would suggest that the operators should be available only if applicable to the attribute selected. For example if i select a string `include` is not visible in the dropdown or if i select a boolean `greater than` is not visible.

**Comment by sseppi** [comment]
Sure! Is the same functionality.
