### ISSUE TITLE
Filtering error: Incorrect Data Filtering with includes

### ISSUE THREAD

**Issue by lukmay** [noi-techpark/it.bz.opendatahub.databrowser#381]
Device: Desktop
Operating System: Windows 11
Browser: Chrome, Firefox
Problem Description:
The filter `includes` doesn't return the correct data because the used URL is not in the right format.

Example on [Open Data Hub Tags - Dataset](https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Tag):

![grafik](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/86775313/d80d8f31-af56-4cf4-b471-4d6c70e86235)
This filtering gets me on the following page:
![grafik](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/86775313/8756618f-0b97-417d-8750-22ed5f675899)
The URL created by this filtering is this: 
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Tag?rawfilter=and(in(PublishedOn,%27idm-marketplace%27))&rawsort=Id

The Issue is that the Data field (in this case, `PublishedOn`) is not traded like an array.
To solve the issue manually, we can add `.[*]` to it.

So the URL should look like this to work:
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Tag?rawfilter=and(in(PublishedOn.[*],%27idm-marketplace%27))&rawsort=Id

**Comment by sseppi** [comment]
@gappc thank you now it seems to work fine. How would you suggest to put this bugfix in production, alias beta version?
Since this issue comes from a feedback of an external user that started to use the Data Browser beta, I would like to go online with the bugfix as soon as possible.

**Comment by gappc** [comment]
@sseppi I would just release the current version (merge development branch into main branch) as usual.

**Comment by sseppi** [comment]
@gappc OK, I would do so. Can you please notify me and @lukmay as soon as the bugfix is in production. So we can answer to the customer who opened the ticket?

**Comment by gappc** [comment]
@sseppi @lukmay the changes are now in production
