### ISSUE TITLE
Access enpoint table view from dataset table view

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#382]
- **Device**: Desktop
- **Operating System: Ubuntu 20.04
- **Browser:** Brave ([Versione 1.51.118 Chromium: 113.0.5672.126 (Build ufficiale) (a 64 bit)](https://brave.com/latest/))
- **Problem Description:**
I did the following steps:
  - access the Data Browser 2.0 (https://v2-beta.databrowser.opendatahub.com/)
  - access the list of all dataset (https://v2-beta.databrowser.opendatahub.com/dataset-overview)
  - access the table view of the NOI Techpark Events from the list of all datasets (https://v2-beta.databrowser.opendatahub.com/dataset/table/tourism/v1/EventShort?source=noi)
![Schermata da 2023-05-23 11-37-08](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/74f1b50e-b0bf-4a53-b52c-b2fa4a0c81d0)
As you can see in the screenshot, there is no active filter shown in the filter and the user doesn't have any possibility to reset the filters and get all Events provided by the Endpoint.
  
- **Expected behaviour:**
The user should have always the possibility to easily access all records provided by the endpoint. In this case all events provided by the ``EventShort`` Endpoint.

Since for the filtering we didn't use the ``rawfilter`` functionality, I think it would be difficult to show the selected filter in the right toolbox and allow him to reset all filters by using the ``Reset all filters`` button. Maybe a possible solution could be, to let become the endpoint name in the TableView title clickable and allow the user to access the table view of the entire endpoint by clicking on it.
![Schermata da 2023-05-23 11-48-29](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/05a147d6-0e46-4d61-927f-b922bd4c6cf6)

**Comment by sseppi** [comment]
@gappc thank you for your feedback, maybe @pkritzinger and @Mazzolintis can bring their opinion at the next refinement meeting so we can then plan the improvement in one of the next iterations.

**Comment by gappc** [comment]
@sseppi during the changes due to #372 I have implemented your proposal.

You can take a look at it e.g. here: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Article?source=noi

Please let me know what you think about it.
