### ISSUE TITLE
As a Open Data Hub developer I want that Deprecated endpoint are hidden from the list of Dataset, to avoind to give visibility to deprecated endpoints

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#389]
By testing the Data Browser I noted that also deprecated endpoint (``"Deprecated":true``) are visible in the ``Dataset Overview``:
https://v2-beta.databrowser.opendatahub.com/dataset-overview

![Screenshot from 2023-06-08 08-53-55](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/1489ee18-4e20-4fba-8c6b-cf0f48854007)

I would suggest to so:
- hide the deprecated endpoints and all dataset related to deprecated endpoints from the ``Dataset Overview``;
![Screenshot from 2023-06-08 08-54-33](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/7458083f-533b-4a5a-b077-1518d5913c7b)
- allow users to access the deprecated endpoints/datasets only by  having the direct link (e.g. for Activities the only way to access should be: https://v2-beta.databrowser.opendatahub.com/dataset-overview/2e718b01-ba5b-43a9-91d6-f9cb32e1a6c9)

We don't have to give visibility to deprecated datasets/endpoints since those datasets/endpoints will be shut down after 2 years of deprecation. So we have to avoid that new Open Data Hub data consumer starts to using it.

@pkritzinger @gappc what do you think?

**Comment by pkritzinger** [comment]
@sseppi @gappc I had a look at it and think that the current solution is pretty good? Showing that a dataset is deprecated could be a relevant information for people who have implemented its API. Or where do they get that information from? Maybe we could create a badge for deprecated datasets and also show when they will be shut down? 

![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/92454516/9a2cc0d7-7f99-4c31-ad48-03a30ed09f10)

**Comment by sseppi** [comment]
Hi @pkritzinger ,

thank you for your feedback and I will try to answer you below. 

> @sseppi @gappc I had a look at it and think that the current solution is pretty good?

Be worry, the deprecation information you marked in the screenshot in the Title has been put by me and not automatically.

> Showing that a dataset is deprecated could be a relevant information for people who have implemented its API. Or where do they get that information from? 

The communication of deprecation will be done through other channels that the Data Browser. For example we send periodically emails to our community to communicate this things. Moreover, people that are already consume the data from deprecated APIs will still have access to it through a direct link.

The experience we have, is that if we leave the Dataset in the list with a Deprecated label, people ignore this information and use the deprecated calls anyway. For this reason we internally agreed to hide the deprecated datasets from the Dataset Overview.

> Maybe we could create a badge for deprecated datasets and also show when they will be shut down?

Good idea to have a badge, so also people that have a direct link will have a clear information.

**Comment by sseppi** [comment]
The team agreed to proceed with the idea proposed in the previous comment.

The only feature to be added is the possibility to activate also deprecated endpoints. Per default the Dataset Overview will list onli non deprecated dataset/endpoints.
