### ISSUE TITLE
Fix icon in the filter button

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#400]
@gappc can we pls. change the icon of the filters as in the design?

Frontend: 

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/92454516/157f2ff6-b063-4a51-ba6a-b97a357c98b4)

Design: 

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/92454516/52e57a27-f5e3-4735-b9ce-e20aba861af5)

_Originally posted by @pkritzinger in https://github.com/noi-techpark/it.bz.opendatahub.databrowser/issues/72#issuecomment-1597319912_

**Comment by gappc** [comment]
@sseppi @pkritzinger fixed as of e8c90fcd7a471c7044788d018373858893d4c69b

You can take a look at it e.g. here: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation?rawfilter=and(eq(AccoTypeId,%27BedBreakfast%27))

If it's ok, please close this issue

**Comment by pkritzinger** [comment]
@gappc thanks, ok for me - issue can be closed from my pov @sseppi

**Comment by sseppi** [comment]
@gappc fine for me as well.
