### ISSUE TITLE
the basic search doesn't work on the meta data dataset

### ISSUE THREAD

**Issue by d3liaa** [noi-techpark/it.bz.opendatahub.databrowser#406]
I tried to use the basic search in the metadata dataset but it didn't work. It showed always every result. 
(The filtering works)

link i tried: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/MetaData?searchfilter=noi
meta data dataset : https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/MetaData

**Comment by RudiThoeni** [comment]
Added the searchfilter for the Fields
`Shortname,
ApiDescription`

**Comment by sseppi** [comment]
@RudiThoeni thank you for the quick fix!

@d3liaa can you please test if it works as expected on the Data Browser side?

**Comment by sseppi** [comment]
@d3liaa did you tested? Is it everything working as expected now?
