### ISSUE TITLE
Change footer link to correct URL once it exists

### ISSUE THREAD

**Issue by henri-egger** [noi-techpark/it.bz.opendatahub.databrowser#415]
This is a reminder to change the link of the contributors text of the page footer ance a contributors section exists on the Open Data Hub website.
For the moment i made it link to https://opendatahub.com/community#contributors, if no new page like https://opendatahub.com/community/contributors gets created, this url is fine and doesn't need to be changed.

**Comment by henri-egger** [comment]
On Emilys request also mentioning @emilylouisesimonis, @ila131, @taniamarcadella.

**Comment by gappc** [comment]
@sseppi is this issue still relevant?

**Comment by sseppi** [comment]
@gappc yes, we need to update the website and then update the link in the footer to link to the right section.
