### ISSUE TITLE
As an Open Data Hub Data Browser user I want to filter all element that contains a certain value, to easily find what I'm looking for.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#424]
As you can see in the documentation linked below, a new feature has been added to the ```rawfilter``` has been added.

https://github.com/noi-techpark/odh-docs/wiki/Using-rawfilter-and-rawsort-on-the-Tourism-Api

The ```rawfilter``` includes now the features ```like``` (for strings) and ```likein``` (for array of strings) that allows the user to filter out all elements that contains a certain substrings in a field or in array.

I post here below the example that returns all eventShort that in the Title contains "SFS":
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/EventShort?source=eurac&rawfilter=and(like(EventTitle.en,%27SFS%27))

I post here below the example that returns all EventShort that has a language that contans "d":
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/EventShort?rawfilter=and(likein(HasLanguage.[*],%27d%27))

**TODO**: include the ```like``` and ```likein``` operators in the filter options (see screenshot below).

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/6a0e7de3-c647-4ab7-ab10-7790e2dec76d)

**Comment by gappc** [comment]
Done as of [638c4f6](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/commit/638c4f6f237279451502bb26b8ddc5aaeb48d9a4)

**Comment by sseppi** [comment]
Super that is a great news! I will test the functionality and close the issue!
