### ISSUE TITLE
Make GpsInfo the source of truth for GPS data

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#435]
>> Note: this issue was created as followup to issue #425 and its comment https://github.com/noi-techpark/it.bz.opendatahub.databrowser/issues/425#issuecomment-1770993493

> We defined on our meeting:
>
> In future `GpsPoints` will be the Property to read and write.
> - A component will be created for GpsPoints where more GPS Points can be added, we have to ensure that the key "position"  is always present
>
> Rudi informs the team when the root field `GpsPoints` is set from readonly to writeable. All other root fields (flat >Latitude,Longitude....... GpsInfo etc...) will be set to readonly
           
**30/10/2023**
We defined on our meeting:

In future `GpsInfo` will be the Property to read and write.
- A component will be created for GpsInfo where more GPS Points can be added (since we don't have to ensure that the key "position"  is always present anymore, can we reuase the same component we use for other lists/array?)

Rudi informs the team when the root field `GpsInfo` is set for all datasets. All other root fields (flat Latitude,Longitude....... GpsPoints etc...) will be set to readonly.

**Comment by sseppi** [comment]
@gappc can we move in testing this issue with the  changes are merged as of commit https://github.com/noi-techpark/it.bz.opendatahub.databrowser/commit/f3c0bd9cc38e17e1f40dd1662792ccb652d1c92c ? Or do yo need to make further checks?

**Comment by gappc** [comment]
@sseppi this issue is a followup issue on #425

#425 is concerned about changes to the WebcamInfo model, while this issue here is concerned about changes to the GpsPoints model. This issue has a dependency on Rudis changes on the backend.

**Comment by sseppi** [comment]
OK, everything clear to me! @gappc Thank you for the explanation.

**Comment by sseppi** [comment]
@gappc @RudiThoeni 

As emerged in issue #360 this week emerged a critical aspect in using ```GpsPoints```as source of truth per GPS coordinates.
We probably have to use the ```GpsInfo```instead.

As mentioned in the issue #360 we propose to have a meeting on Monday 30 October between 9 and 11 am.

**Comment by sseppi** [comment]
@gappc 

Today me and Rudi had the planned meeting and we decided together to use the ```GpsInfo``` as source of truth for the GPS data. The decision was made, since the ```GpsInfo``` is easier to handle from a Data Provider and front-end point of view.

@RudiThoeni will implement the ```GpsInfo``` field in all endpoints and make a sync script between ```GpsInfo``` and ```GpsPoints``` in order to keep them in sync for a certain period. This means that the ```GpsType``` hasn't constraint anymore and can be set freely by the user. Rudi, in case 

- there is no ```GpsType=position```
- there is more ```GpsType=position```
- there isn't any ```GpsType```

, will manage it properly in the sync script between ```GpsInfo``` and ```GpsPoints```. 

The ```GpsPoints``` will be set as ReadOnly and marked as deprecated. This means that in the Data Browser the user will have the possibility to modify only the ```GpsInfo```.

**Comment by sseppi** [comment]
@RudiThoeni thank you for the update!

@gappc I think you can now update the components and configurations in the Data Browser.

**Comment by gappc** [comment]
@sseppi @MatteoBiasi is this issue still relevant or are the changes already in place?

**Comment by sseppi** [comment]
@RudiThoeni from your side the changes and configuration has been concluded?

**Comment by RudiThoeni** [comment]
From my side all concluded GPS Component seems to work fine
