### ISSUE TITLE
As a Data Browser user I want a header height reduced to the minimum, to have more space for the data.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#437]

**Comment by sseppi** [comment]
@pkritzinger : can you please share the new design proposed?

**Comment by pkritzinger** [comment]
hi @sseppi 
Here's the link to the respective section:
https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?type=design&node-id=1508%3A12031&mode=design&t=Ha38KlFfOl45aW1j-1

Some remarks:
- We had to integrate the ODH-Logo in the burger menu on mobile devices. Otherwise it would have been in conflict with the icon of the burger menu.
- Shall we also rethink the footer. From our perspective we should remove the ODH-Logo (see Screenshot)

![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/92454516/218a9e3e-db63-419b-92f5-8f85775a8ae1)

**Comment by sseppi** [comment]
Hi @pkritzinger,
thank you for the proposal.
Please find below my answers.
> Some remarks:
> 
> * We had to integrate the ODH-Logo in the burger menu on mobile devices. Otherwise it would have been in conflict with the icon of the burger menu.

Fine for me

> * Shall we also rethink the footer. From our perspective we should remove the ODH-Logo (see Screenshot)
> 
> ![image](https://user-images.githubusercontent.com/92454516/277656663-218a9e3e-db63-419b-92f5-8f85775a8ae1.png)

I agree, the Open Data Hub logo should be removed also in the footer.

**Comment by pkritzinger** [comment]
@sseppi thanks for your feedback. We made the changes in the file - it's ready to code :)

**Comment by sseppi** [comment]
@MatteoBiasi now you can start the estimation of the implementation of the changes.

**Comment by RudiThoeni** [comment]
@sseppi please test for me it seems fine

**Comment by sseppi** [comment]
@RudiThoeni I tested and it seems fine to me too.

@pkritzinger in your point of view, wouldn't be better to open the `How To` and `Contact` links in a new window, since they are externa links?

**Comment by pkritzinger** [comment]
Agree with @sseppi that we should open the links in a new tab. 
Further, we suggested to improve the Login/ Register-Logic by means of an icon and an expandable menu. See Screenshot below: 
![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/92454516/6790b378-5dd9-44c7-8f26-847f8dd4dfe7)

This optimization is not a must but in case there should be additional time it could be added to one of the Product Phases.

**Comment by sseppi** [comment]
@pkritzinger thank you for the feedback.

@MatteoBiasi can you please fix the two proposals in the comment above (open the two links in ne window and improve the login/register icon).

**Comment by sseppi** [comment]
@MatteoBiasi while testing I noticed that the boxes in the footer aren't clickable anymore. 

If I click on the Open Data Hub box in the center I would like to open in a new window the Open Data Hub website (https://opendatahub.com/).
If I click on the NOI box (the right one) I would like to open in a new window the NOI website (https://noi.bz.it/).

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/386d981d-1ea8-431e-aedf-a12677382b66)

Can you fix this problem?

THX

**Comment by MatteoBiasi** [comment]
@sseppi we added the links; here it's the PR: https://github.com/noi-techpark/it.bz.opendatahub.databrowser/pull/529. PS: this was not a bug introduced by us. You can see [here](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/commit/8ee6dcc7428d1b12216020a0e8974d042ad4eac4) that it was the original implementation of Heniry that was without the links.
