### ISSUE TITLE
SelectWithOptionsCell once click +ADD NEW impossible to cancel input

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#449]
By clicking on the `+ADD NEW` button on a Select Box it gets correctly activated the possibility to input a new value as String.

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/97cabfa5-ccdf-47d5-9d6e-dbfc4ff25c04)

 As you can see in the screenshot below, once the string input has been activated there is no way to get back to cancel the input via string and go back to the select box.

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/dba9be0a-cb14-44ff-a164-c983ab4c3804)

Shall we introduce a small `Back button` like for example a small `x` (See screenshot preview below) to go back from the String input field to the select field?

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/c9e0b227-f932-44c9-8196-9f409d7cfb94)

To reproduce the problem I used the following steps:

1. Access the *Dataset Information* dataset: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/MetaData
2. Access the edit view of one dataset, as for example *Horses*: https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/MetaData/054e3e27-61a4-41ea-867f-fc97b275cef1
3. Add a new Data Provider
4. Select +ADD New from the dropdown

**Comment by sseppi** [comment]
@pkritzinger and @Mazzolintis : what do you think about this issue? Shall we foresee this improvement in the next iteration we do?

**Comment by pkritzinger** [comment]
@sseppi sounds good, let's do that!

**Comment by sseppi** [comment]
@MatteoBiasi we should plan also this small change to the component, to improve the usability of it.

**Comment by RudiThoeni** [comment]
@sseppi  tested and it works

**Comment by gappc** [comment]
@sseppi I think we can close this issue, what do you say?

**Comment by sseppi** [comment]
Fine also for me.
