### ISSUE TITLE
Error in the Console After changin something in the Edit view and clicking Cancel.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#450]
Testing the latest version of the Data Browser in localhost we noticed an error that appears in the console if we do the following steps:

1. Access the edit view of a random record
2. change something
3. click on `Cancel` to exit for the Edit View without saving the changes

After clicking on `Cancel` in the console it appears the error you see in the following screenshot.

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/3a892692-c907-46a1-9fa6-b24dd616b1da)

**Comment by RudiThoeni** [comment]
ok @sseppi  issue can be closed

**Comment by sseppi** [comment]
@RudiThoeni OK, thank you for the feedback!
