### ISSUE TITLE
As a developer I want to have additional Components

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/it.bz.opendatahub.databrowser#451]
Quick draft to find out which components are needed for the ODHActivityPoi Endpoint

## LicenseInfo

The Component to set the Licenseinfo is missing (seems we can configure this without a component)

```javascript
"LicenseInfo": {
	"License":	"string",
	"LicenseHolder": "string",
	"Author":	"string",
	"ClosedData":	boolean
}
```

## Mapping

The Mapping Component shows possible properties of interest of one or more sources where no appropriate field exists. At example it could contain the SkiresortId on Dolomitii Superski etc... Fields like `CustomId`, `SmgId`, `OutdooractiveID`, `HgvId` etc... will be marked as obsolete and added into the Mapping Property.  
Since it is a Dictionary<string, Dictionary<string,string>> i think we have to create a component for managing this data?

```javascript
"Mapping": {
     "dss":  {
        "regionId": "12",
        "skiresort_pid": "53",
        "skiresort_rid": "173"
     }
}
```

## RelatedContent

The actual RelatedContent Webcomponent is not what we need
![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/30471361/560a0284-8346-4158-920d-602a6c89af7f)

it simply populates a string field `"RelatedContent": "aaa"` which does not correspond to the datastructure

The datastructure of RelatedContent is:

```javascript
"RelatedContent": [
{
"Id": "90e4bef8-3a43-4d82-bde7-0b1f77c6edf2",
"Self": "https://api.tourism.testingmachine.eu/v1/WineAward/90e4bef8-3a43-4d82-bde7-0b1f77c6edf2",
"Type": "wineaward"
},
{
"Id": "smgpoi710",
"Self": "https://api.tourism.testingmachine.eu/v1/ODHActivityPoi/smgpoi710",
"Type": "odhactivitypoi"
},
{
"Id": "0ecf738f-0627-4747-8ccd-6a07a9b6536b",
"Self": "https://api.tourism.testingmachine.eu/v1/WebcamInfo/0ecf738f-0627-4747-8ccd-6a07a9b6536b",
"Type": "webcam"
}
]
```

I added into the openapi spec all possible values for the field `Type`

![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/30471361/935db8e6-de0e-4309-a0f8-0e6c3e11afba)

I think we have to create a component here.

## GpsInfo

As described in the other issue we need a Component where we can set all GPSInfo. I added to the openapi spec the possible values for the field `Gpstype`
![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/30471361/27cb98ba-4a08-4c60-bb4a-555d527a0834)

## AdditionalPoiInfos

Language Based, for us for Interest is the field `Novelty` and the field `Categories` to check if the field Categories can be populated on save.

## PoiProperty 

Language Based Key/Value List to store all fields where there is no corresponding field in the Datamodel. Generic and useful for all Datasets. Maybe here we need also a Property where the Key/Value List is not language based. 

```javascript
"PoiProperty": {
"de": [
  {
  "Name": "openingtimesgastronomie",
  "Value": "März bis Dezember"
  },
  {
  "Name": "hasvisits",
  "Value": "False"
  }
]
}
```

## Gastronomy Infos

There are some fields which contains Infos about a Gastronomy which are not displayed. To check if we need to create a component here

CapacityCeremony  
CategoryCodes  
DishRates
Facilities
MaxSeatingCapacity

## ChildPoiIds, MasterPoiIds

To check where we have to show this assignments, to discuss if this assignment can be shifted to another already present generic field

## VideoItems

Todo Component for adding Videos

## DistanceInfo

Todo Config for adding the fields for DistanceInfo

## GpsTrack

Current Datamodel is:
```
"GpsTrack": [
{
"Id": null,
"Type": "detailed",
"Format": "kml",
"GpxTrackUrl": "https://www.dolomitisuperski.com/file/?uuidSlope=8ab7c307-7cf1-471e-8577-6a80927a1cd2",
"GpxTrackDesc": { "de":"test" }
}
],
```

**Comment by sseppi** [comment]
@RudiThoeni thank you for the great overview!

As discussed before, I would suggest to wait till the next meeting with Delia and then plan what is feasible simply by optimizing the configuration of the single datasets and what should be implemented in a new component.

**Comment by sseppi** [comment]
@RudiThoeni is this issue still valid? Can we chek if we need all the compoent yoou mentioned above?

**Comment by RudiThoeni** [comment]
right only GpsTrack is missing, we can close this issue and open another for the gpstrack component only what do you think @sseppi ?

**Comment by sseppi** [comment]
OK Fine, the issue for the implementation og the GPSTrack is the #361
