### ISSUE TITLE
"SelectWithOptionsCell" Invalid prop error

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#452]
By running  the Data Browser in localhost and for example tying to access the following link 

http://localhost:3000/dataset/edit/tourism/v1/MetaData/00109544-2a58-4051-b619-b350e0035d20

I get the following error message

```
[Vue warn]: Invalid prop: type check failed for prop "showAddNewValue". Expected Boolean, got String with value "true".
  at <SelectWithOptionsCell value="tourism" showAddNewValue="true" showValueAsLabelFallback="true"  ... >

```
Probably the problem is due to the fact that the component expects a boolean parameter, but the WebComponents are able to handle only Strings.

From a first analysis the team did, we see 3 possible solutions:

- improve the documentation and explain clearly that the WebComponets are able to pass only Strings. And then change all components accordingly.
- modify the implementation in a way that is possible to pass not only strings for the Vue components and introduce a fallback strategy for the WebComponents
- remove the support to WebComponents (We wouldn't go this way)

**Comment by sseppi** [comment]
@MatteoBiasi will change the code to pass a string and improve the documentation explainig that in the actual implementation the components accept only Strings.

@gappc  will post a comment in the `ComponentRenderer` code (https://github.com/noi-techpark/it.bz.opendatahub.databrowser/blob/development/databrowser/src/components/componentRenderer/ComponentRenderer.vue) wit the proposal of the optionimazion (allow to passo object to Vue components and only strings to Web Components) that will be implemented in the future.

**Comment by gappc** [comment]
@sseppi I think we can close this issue, what do you say?
