### ISSUE TITLE
"SelectWithOptionsCell" error: "Missing queryFn"

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#453]
The "SelectWithOptionsCell" generates sometimes an error "Missing queryFn" (see screenshot below; note that the screenshot is from localhost to show the error details, but the problem appears also on the current TEST environment).

Steps to reproduce:

- open e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/Article/6EF8FF7B-6BC6-4FED-E94C-03D817F9492A#main-data
- click on the Category "Text Information", then back to "Main data". Repeat this step until the error shows up

The reason seems to be the way the component input is handled.

![image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/5732768/9ff12da9-56f3-4f4b-853a-d57a9f16f3e1)

**Comment by gappc** [comment]
@sseppi I think we can close this issue, what do you say?

**Comment by sseppi** [comment]
I don't get the error anymore. I close the issue.
