### ISSUE TITLE
As an Open Data Hub Content Editor I want to be able to delete the content I'm responsible for, to remove wrong records.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#460]
We need to implement as soon as possible the delete functionality, since some user are asking for it.

One idea could be to add a button `Delete` in the right column in Table view.

Shall we add a the delete functionality also in the detail, edit and raw view?

**Comment by sseppi** [comment]
@pkritzinger and @Mazzolintis can you please elaborate a proposal for the next meeting?

**Comment by pkritzinger** [comment]
@sseppi I think we can do that, yes. 

Questions:
- Would this feature always refer to records, not to attributes, correct?
- Any specific roles we have to consider (e.g. I am only allowed to delete records a created)?

**Comment by sseppi** [comment]
@pkritzinger please find the answers below.

> * Would this feature always refer to records, not to attributes, correct?

Right.

> * Any specific roles we have to consider (e.g. I am only allowed to delete records a created)?

Yes, the deletion of the record will be allowed only to specific roles. The Open Data Hub API, as does for the write roles, will provide the information about the delete permissions to the data browser.
For the moment this information will be provided only at a Dataset level, but in future it will be provided at a record level. This means that, a user will have the rights to edit/delete only a subset of all records included in a dataset.

**Comment by pkritzinger** [comment]
Thanks @sseppi all clear :)

**Comment by sseppi** [comment]
@pkritzinger can you please share the link to the design you presented today during the meeting?

**Comment by pkritzinger** [comment]
@sseppi @MatteoBiasi eccolo :)

https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?type=design&node-id=1775%3A4859&mode=design&t=2kGDcpXSS4qLt0eq-1
