### ISSUE TITLE
Add new publisher doesn't work in testing

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#468]
I tried to add a new event and modify the following event provided by the EventShort APIs:

https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/EventShort/eventshort-11378

While doing this changes I tried also to add a new publisher and I got the following error.

``` 
Error!
Cannot read properties of undefined (reading 'value')
```

![Schermata da 2023-12-05 11-26-25](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/2eab2c7c-624a-4f5a-9006-68d9ef4adb5e)

I tried the same on the Beta and Production environment and there the functionality is working fine.

**Comment by sseppi** [comment]
@gappc @RudiThoeni I assigned both of you since I saw you did the last merged PRs, can you please check what is the problem?

**Comment by RudiThoeni** [comment]
@sseppi sorry it was my fault ;) corrected on api side!

**Comment by sseppi** [comment]
@RudiThoeni thank you for fixing! Now it works!
