### ISSUE TITLE
Keycloak Logout not working

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/it.bz.opendatahub.databrowser#479]
On logout we get a `We are sorry...
Missing parameters: id_token_hint`

Currently only on Testing

**Comment by RudiThoeni** [comment]
also to check i noticed this warning
`AppLayout.vue_vue_type_script_setup_true_lang-dd887688.js:8 [KEYCLOAK] Instantiation using the `Keycloak` function has been deprecated and support will be removed in future versions. Use the `new` operator to create an instance instead.`

**Comment by RudiThoeni** [comment]
after some cache/cookies clear the login/logout now works normally and i am note able to reproduce this error......

**Comment by gappc** [comment]
@RudiThoeni does the problem still happen or can we close this issue?

**Comment by sseppi** [comment]
Now the logout is working on my side. I close the issue
