### ISSUE TITLE
Matomo integration missing or broken

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/it.bz.opendatahub.databrowser#502]
Bug: Since February 2023 we are not recording any webstats about the Data Browser in Matomo anymore. Please see screenshot attached.

![Screenshot from 2023-12-25 12-30-32](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/414797/6b9f08d3-3541-49ba-aa07-ce1dfa8b1bbd)

- [ ] add matomo to the data browser and have stats collected.

**Comment by gappc** [comment]
Hey @dulvui, I saw that you've changed the Matomo ID in https://github.com/noi-techpark/it.bz.opendatahub.databrowser/commit/c3bc33ff7845087fa85a556bfd249b88388a970b. Does that fix this issue?

**Comment by dulvui** [comment]
@gappc Yes, now the correct Matomo ID is used and the data shows up on this dashboard.
