### ISSUE TITLE
As STA and independentL I would like to use the Data Browser in order to upload additional metadata (accessibility information) of the public charging stations

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/it.bz.opendatahub.databrowser#505]
Expected workflow:
- [x] STA / IndependentL, thanks to proper user privileges, can access the Data Browser and add metadata to e-mobility stations
- [x] The list of metadata is available in this attachment. It is also foreseen to add images of the charging stations.

[231002_IndependentL_Vorschlag-Erhebungsdaten.pdf](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/files/13916861/231002_IndependentL_Vorschlag-Erhebungsdaten.pdf)

Test environment: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/ODHActivityPoi?tagfilter=electric+charging+stations

Additional requests:
- [x] Because of technical reasons (i.e. possibility of "physical" identification of charging points), we need to have in the Data Browser also the stations that have station type = 'EChargingPlug' - https://mobility.api.opendatahub.com/v2/flat,node/EChargingPlug/*/latest
- [x] IndependentL asks to have the names of the additional data types in 3 languages (see attached below). My proposal would be to have them just in English
- [x] IndependentL would like to use the Data Browser during the assessment, with a mobile device (tablet). Following operations should be possible:
- [x] search of the right charging point also through the web component e-mobility. They will use as key the name of the charging station.
- [x] identify physically the charing point, by considering the ID in the charging point name (e.g. E12247045420020*1)
- [x] write the values for the additional fields foreseen, including photo upload

To do: 
- [x] final review with IndependentL about fields presence / order / naming
- [x] joint field test session in order to joint evaluate the UX
- [x] final fine tuning of the Data Browser (if necessary)
- [x] deployment on production

[24-08-06_Vorschlag-Erhebungsattribute Traduzione.xlsx](https://github.com/user-attachments/files/16588092/24-08-06_Vorschlag-Erhebungsattribute.Traduzione.xlsx)

**Comment by clezag** [comment]
@rcavaliere I've had a look at the draft, and in my opinion putting this into station metadata could lead to a bunch of issues, and it looks much more like POI data in tourism. Even more so if we think about the domains as timeseries vs content.

So before starting with any implementation, I will have a discussion with Rudi to see what similar data he currently has, and explore if and how it could potentially be put into tourism and linked with the mobility API

In addition, Antonietta has brought up that IDM and LTS are themselves in talks with IndependentL about getting accessibility data in the tourism space. Maybe we can find out what they are talking about about, there could be overlap with this issue. e.g. maybe it turns out that in the end we can have a single data stream of accessibility data, combined into a new POI accessibility data set, and link to it from the mobility side.

**Comment by rcavaliere** [comment]
@clezag @RudiThoeni that's fine for me. But remember that we also have to provide them a possibility to give this data to the Open Data through the Data Browser. They are already waiting us in order to start the data upload. Please find here attached an example of accessibility data associated to a charging station.

[TESTERHEBUNGEN.zip](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/files/14066401/TESTERHEBUNGEN.zip)

**Comment by RudiThoeni** [comment]
I will check this in this sprint.
With the latest changes on the Authorization System on Tourism it should be possible to manage that only certain POIs can be edited by some Independent User

**Comment by RudiThoeni** [comment]
@clezag can you provide me the call to get all the public charging stations from the mobility api so i can insert them as pois into the tourism api

Next steps are

- [ ] Sync Pois from Mobility api
- [ ] Create Data Schema
- [ ] Extend the Databrowser to allow insertion of this data
- [ ] Because this data insertion section will be visible for all Activities and POIs on the opendatahub, maybe we should add a configured view prefiltered on echarching stations which only shows this section, not sure if this is possible

**Comment by RudiThoeni** [comment]
@rcavaliere what is the call to get the E-Chargingstation which i should import as Poi, because this here returns a lot :) https://mobility.api.opendatahub.com/v2/flat/EChargingStation/*/latest?limit=0

**Comment by rcavaliere** [comment]
@RudiThoeni I would just import the metadata of the stations -> https://mobility.api.opendatahub.com/v2/flat,node/EChargingStation?limit=0 probably you should just consider the active stations, then https://mobility.api.opendatahub.com/v2/flat,node/EChargingStation?limit=0&wheresactive.eq.true

**Comment by RudiThoeni** [comment]
ok and consider only stations in south tyrol or all?

**Comment by rcavaliere** [comment]
you are right, just South Tyrol could be sufficient now. @clezag can you provide here the API call with the bounding box you defined for the web-components with the KPIs (https://webcomponents.opendatahub.com/webcomponent/mobility-e-charging-dashboard)

**Comment by clezag** [comment]
Yes, already shared that with Rudi.
Something like https://mobility.api.opendatahub.com/v2/flat/EChargingStation/?limit=0&where=sactive.eq.true,scoordinate.bbc.(10.377487,46.141620,12.485895,47.105445,4326)

**Comment by rcavaliere** [comment]
First release by @RudiThoeni - test environment: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/ODHActivityPoi?tagfilter=electric+charging+stations

@rcavaliere is testing and checking if everything is OK. Then we will then set up everything so that IndepententL can start uploading their data

**Comment by rcavaliere** [comment]
@RudiThoeni today I was finally able to test your development. Looks everything OK, I think IndependentL should have everything for their activity! I will then start contacting them so to introduce the tool.
I will ask for the user details that should have access grants with edit power for this specific data.
Shall we work directly in production mode or better organize some tests in the testing environment? In the first case, we should set up the production environment first

**Comment by RudiThoeni** [comment]
Hi @rcavaliere I can also deploy everything on production and we start from there...... will inform you when done...... The first step is they register an user on keycloak and i assign the rights to access and edit the data....... They can already do it... go to https://databrowser.opendatahub.com/  then on login go to `New user? Register` fill out the Registration Form and give us the names so we can set up everything.......

**Comment by rcavaliere** [comment]
@RudiThoeni the users are:

- Anita Stizzoli (Anita.Stizzoli@independent.it)
- Marianne Viskanic (Marianne.Viskanic@independent.it)
- Günther Ennemoser (Guenther.Ennemoser@independent.it)

Can you please create them and set up the access rights?

**Comment by RudiThoeni** [comment]
@rcavaliere  the process is that they register on keyckloak setup their password etc... after this is done i will add the access rights
https://databrowser.opendatahub.com/
Right above Login --> New user? Register

**Comment by rcavaliere** [comment]
@RudiThoeni thanks. In the meantime, I imagine they can do the same also in the testing environment, isn't it? They would like first to make some tests here. Another request: would it be possible to put the coordinates as additional column in this view?

**Comment by rcavaliere** [comment]
@RudiThoeni perfect, I give her feedback that she has already grants!

**Comment by rcavaliere** [comment]
@RudiThoeni feedback from IndependentL shared via mail. They request to have the view at plug level and to make some changes to the available fields, both in the general list and in the station detail

**Comment by rcavaliere** [comment]
Blocked until STA and IndependentL understand how to manage the accessibility characterization at plug level

**Comment by rcavaliere** [comment]
@RudiThoeni @sseppi I have put in the main description of the user story the detailed requests of IndependentL that we need to analyze together. I will now organize a joint meeting to discuss them

**Comment by rcavaliere** [comment]
@ohnewein @sseppi @RudiThoeni @clezag short summary about our meeting today:

- Front-end: some little fine-tuning needed, @sseppi will get next week a feedback for the implementation time needed. Should not be critical
- Back-end: some tasks for @RudiThoeni, i.e. (everything in the testing environment):
- - delete all imported EChargingStation data
- - import from the mobility API the EChargingPlug dataset
- - visualize on the Data Browser the field sname

Other decisions:
- no further sync between mobility and tourism domains after upload of new data by IndependentL. In case applications will have to consume separately the APIs from the two domains, by using sname as key
- multilinguism is not a feature, IndependentL can only insert annotations in different languages. @rcavaliere will explain this to IndependentL.

**Comment by RudiThoeni** [comment]
Hi @rcavaliere 
I changed the dataimport to import each plug.
deleted the old one and reimported all data

For scode,sname i was not sure.......
There are often strange names, at example here
```javascript
"scode": "Leitner Energy:CSU Soc. Coop. - Parkdeck - 11kW - Bozen/Bolzano - A. Volta Str. 13/Via A. Volta 13:1",
"sname": "1",
```
So now I am storing
scode as Id prefixed by `echarging_`
sname into Title
both are shown in the Databrowser and it is possible to filter for this values
![image](https://github.com/user-attachments/assets/f554f1ae-f4b0-49b6-874a-6b388129fcc4)

filter on id
![image](https://github.com/user-attachments/assets/ac35f2aa-3cca-4447-8676-82486273b7c4)

filter on title
![image](https://github.com/user-attachments/assets/ed15ad58-2fc8-4bf3-99dc-cc782128e584)


@sseppi I think the "like" should be the default operator in the Databrowser filtering, also noticed that when I am on page 2, the filtering does show "no results found" this is a bug maybe you already inserted it as issue

i think is ready for testing now

**Comment by sseppi** [comment]
> @sseppi I think the "like" should be the default operator in the Databrowser filtering, also noticed that when I am on page 2, the filtering does show "no results found" this is a bug maybe you already inserted it as issue

@RudiThoeni Thank you for the updates and for finding the bug, I will do some testing and create a dedicated issue for it.

**Comment by RudiThoeni** [comment]
@sseppi yes you are right the error is because of the "/" in the Id it is interpreted as a route......... will fix this by simply removing this character.....

But first i need an answer from @rcavaliere if scode or sname or both of them are the fields they are searching / filtering........ 
I think sname is the right field, i will store this field into the title.  
What i could do is also store scode + sname into the Title field so with the like filter it should be searchable both?

But as sais before there are a few examples (see https://mobility.api.opendatahub.com/v2/flat,node/EChargingPlug?select=scode,sname&where=sactive.eq.true,scoordinate.bbi.(10.233765,46.236853,12.568359,47.249407,4326)&limit=0) where sname contains only a number and scode contains the naming, i think this has to be fixed on mobility datacollector side  ;)

Here some examples
```
{
"scode": "Leitner Energy:CSU Soc. Coop. - Parkdeck - 11kW - Bozen/Bolzano - A. Volta Str. 13/Via A. Volta 13:1",
"sname": "1",
},
{
"scode": "ECOGY GmbH:Taser - Seilbahn / Funivia / Cable Car:2",
"sname": "2"
},
{
"scode": "Leitner Energy:Kronplatz - Parkplatz 12 - 22kW - Reischach/Riscone - Seilbahnstraße 10:1",
"sname": "1"
},
{
"scode": "VEK:HYC_150_19BZ00056_Glurns:1",
"sname": "1"
},
```

**Comment by rcavaliere** [comment]
@RudiThoeni the e-charging stations mentioned here are a special case, in this case we don't have an API with real-time data, but just static information. In this case the data is automatically retrieved from this Google Spreadsheet: https://docs.google.com/spreadsheets/d/1ucCQzAVGmvyRpeq-lIPffALQaWcG4LfPakc2mjt79fY/edit#gid=0

I am not sure if IndependentL will evaluate also these charging stations (probably yes), in this case having just sname won't work. So probably what you could do is to implement such a logic:

```
if origin != [one of the organizations listed in this Google Spreadsheet, column "Data Provider"] then consider just sname
otherwise consider scode 
```

**Comment by sseppi** [comment]
@rcavaliere @RudiThoeni thank you for your contribution.

I have a meeting with IndipendentL planned beginning of next week to present our solution. I will keep you updated.

**Comment by rcavaliere** [comment]
Reminder: current functionalities for IndependentL are at the moment in testing environment (Data Browser)

**Comment by sseppi** [comment]
All changes has been put in testing and can be tested at the following link:
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/ODHActivityPoi?tagfilter=electric+charging+stations
