### ISSUE TITLE
Wrong email in contact and support

### ISSUE THREAD

**Issue by d3liaa** [noi-techpark/it.bz.opendatahub.databrowser#520]
Hi all,
i noticed that in the dataset overview page the contact and support instead of help@ is info@.
![Screenshot 2024-01-22 123744](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/101118017/6b8076ec-4cd4-49f9-9991-9a11a6ae38ef)

**Comment by gappc** [comment]
Hi @d3liaa, looks good, thank you 👍

Is it ready to merge?

**Comment by d3liaa** [comment]
yes :)
