### ISSUE TITLE
As a Data Consumer I want in the Table View an easy way to change the dataset I looking, to be quicker in the navigation of the data.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#525]
If I'm navigating a dataset in the Table View, by clicking on the Dataset name top right (see screenshot below), I want to be able to filter, search and browse the dataset list to change the data I looking.

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/b49f59a3-a254-4d86-a678-365e644efd35)

Once the user clicks on the dataset name, an Idea could be to explode the bar and show the list of datasets and the search and filre options, like in the dataset overview page.

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/b7891ce0-2d45-4900-99b9-d8ea3c8b01ce)

**Warning** If we do so, we have to find a way to warn the user about this functionality! Maybe a tooltip or something similar could be useful. Maybe we could consider something similar what Githug (screenshot belo) or google drive with the new features do.

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/bc7e84a9-0434-411d-9924-a3f7367970fb)

**Comment by sseppi** [comment]
@Mazzolintis 

The proposed solution is inline with the goal of this issue. During the call the following aspect has been discussed:

- in the top right part of the site there are a lot of buttons and functionalities in a little space (e.g. info button, access to related dataset, change dataset, configuration, etc.), maybe a better distribution could be find.

**Comment by sseppi** [comment]
For the search on the Table view "Search within Title" we need to identify a way to implement it also for the mobiltiy.

Since in the Tourism the ```searchfilter```does the search on the Title field, on the mobility side we could implement it by making the search on the "Station Name" field.

On mobile the search will be reduced only to a lens icon. If the user clicks on it will be opened the search.

**Comment by sseppi** [comment]
@pkritzinger can you please add the link to the final version of the design?

**Comment by pkritzinger** [comment]
@sseppi @MatteoBiasi please find the design here.
It would be great if @MatteoBiasi could check what influences the implementation of V2 would have on the different components so that we can review - and in case optimize - them.

**Comment by sseppi** [comment]
@MatteoBiasi 

During the today's meeting we agreed that in case the "Embedded view", if exists a configuration, is always the default view that will be loaded if the user changes the Dataset he is viewing.

In case the users will ask to keep their manual configuration, we will evaluate in future if we need to implement a more complex logic to keep the user choice. The logic should differentiate two different cases:

1. the Data Browser changes from Embedded to Generated view on request by the user and in that case stores the information to load always the Dataset with the configuration chosen by the user;
2. the Data Browser changes from Embedded to Generated view automatically because the configuration is missing. In that case shouldn't be stored the information and in case the users jumps to a dataset with a configuration should open the "Embedded view" per default accordingly the user's choice.

**Comment by pkritzinger** [comment]
@MatteoBiasi find the specifications for the new search here:
https://www.figma.com/design/DmuP6Dbv5LzkCNOXrDnWIL/2023-2024?node-id=3115-2213&t=8yuDhiRdxlgUhQHh-1

FYI: @sseppi

**Comment by gappc** [comment]
@sseppi seems to work (see e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation, can we close this issue?

**Comment by sseppi** [comment]
@gappc Yes, the functionality has been developed as expected. A dedicated issue has been created to solve the representation problem of long dataset names: #603 

Therefore we can close this issue.
