### ISSUE TITLE
As a Data Consumer I want to easily access the Table view from the Dataset Overview page, to improve the navigation of the data.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#527]
By testing the Data Browser I have seen that we could optimize the Dataset Overview as follows:

- by clicking in the area within the red square the user should access dicerctly to the Table View
- for each dataset a third butto ```Details``` to access directly the Dataset Description (e.g. https://databrowser.opendatahub.com/dataset-overview/7c8f490d-7b54-4a88-801f-f7669f5aaed9) should be added.

![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/eb2ee18c-6e53-4954-a6cf-30a08231872a)

**Comment by sseppi** [comment]
@Mazzolintis I write here the comments we agreed:

- that, asp proposed by sseppe in the issue description, the whole square will be clickable to access the table view;
- the background color of the clickable area will become light green when mouse is over
- the green button will be used to access more detail and the proposal of text for the button are "MORE INFO ON DATASET" or "ABOUT THIS DATASET"
- the source list won't be clickable anymore and all sources will be displayes in one line
- if the number of sources can't be displayed in one line, the line will be catted with 3 dots at the end and the user, to see all sources, will have to access the more details section

**Comment by sseppi** [comment]
It has been decided to include in this issue also the review of the access flow. The Dataset overview will become the new Home of the Data Browser

**Comment by pkritzinger** [comment]
@sseppi @MatteoBiasi please find the link to the final design here:
https://www.figma.com/design/DmuP6Dbv5LzkCNOXrDnWIL/2023-2024?node-id=2644-3337&t=d5M8J8DHL80jfTxr-1

**Comment by gappc** [comment]
@sseppi seems to work (see e.g. https://databrowser.opendatahub.testingmachine.eu/), can we close this issue?

**Comment by sseppi** [comment]
@gappc Yes, it works as expected.
