### ISSUE TITLE
As a Data Browser user I want that the Deprecated Fields are hidden per default also in the Table view, to not use deprecated values in my calls.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#532]
The idea is to hide the deprecated fileds also in the Table View. A switcher to activate deprecated fields will be provided to the user, as shown in the figma below:

https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023-2024?type=design&node-id=1997-3335&mode=design

**Comment by pkritzinger** [comment]
@sseppi final design is here (same as for referenced attributes)
https://www.figma.com/design/DmuP6Dbv5LzkCNOXrDnWIL/2023-2024?node-id=2451-2368&t=rjZ9BJAms4N0Zyk3-1

**Comment by sseppi** [comment]
@MatteoBiasi as agreed I share the link to the documentation that explains what Deprecated means, to implement the more info button:
https://github.com/noi-techpark/odh-docs/wiki/What-does-%22deprecated%22-mean%3F

**Comment by gappc** [comment]
@sseppi seems to work (see e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation), can we close this issue?

**Comment by sseppi** [comment]
@gappc Yes, I close the issue
