### ISSUE TITLE
As an Open Data Hub News Editor I want to program the push notification in a future moment, to better plan the NOI App notifications

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#545]
Thi issue is a nice to have funtionality we could implementa and it is related to the issue #534

**Comment by gappc** [comment]
@sseppi is this issue a duplicate of #554?

**Comment by sseppi** [comment]
@gappc yes, sorry I close this one since there are mote information in the #554 issue.
