### ISSUE TITLE
As a databrowser user i want to hide certain properties depending on what type the record is 

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/it.bz.opendatahub.databrowser#549]
Hi @gappc 

I have a concrete Usecase where I want to save very "specific" properties into a generic Endpoint like ODHActivityPois.
For this reason i added into the ODHActivityPoi Dataschema a dynamic field to store this information.
It is possible to save different schemas into this dynamic field...

At example now we have to save the Echarging Properties for Each echargingstation. Therefore i created a Databrowser Section. (https://github.com/noi-techpark/it.bz.opendatahub.databrowser/pull/548)
This section shows up on every ODHActivityPoi Edit, so the question is, how much effort would it be to extend the Databrowser to add a condition into the DetailView/EditView for certain sections.

What i mean is to add on the odhActivityPoi.sharedView
```javascript
    locationCategory(),
    gpsDataCategory(),
    echargingdataCategory(),
```
something like this
```javascript
    locationCategory(),
    gpsDataCategory(),
    %A condition that this section shows only up when the Tags contains a category "echarging"% echargingdataCategory(),
```
What would be a simple, easy and reusable solution for this?
thx and cheers
Rudi

**Comment by RudiThoeni** [comment]
Another option could be to create a specific Configuration for Echargingstation, and if the prefiltered dataset with Echargingstations is opened this configuration is used instead of the generic odhActivityPoi Configuration....
Maybe the MetaData Api could be extended to have an optional information which configuration should be used?

What do you think about this

**Comment by pkritzinger** [comment]
> https://5.databrowser.gappc.net/dataset/edit/tourism/v1/ODHActivityPoi/echarging_it*220*ebz000043#additional-properties

>-There should be the possibility to choose which Additional Property can be added (restricted to only one Additionalproperty, in future could be we need to add more than one). The List of Additional Properties to add is simply configured in the databrowser (maybe future extension could be to retrieve it from an api, but for the moment let's do it hardcoded)
-Then we need also the functionality to remove an Additionalproperty. This removal will delete the content of the Additioalproperty (simply remove it from the Dictionary). This means we have to ask for confirmation.

@gappc @RudiThoeni did I get you correctly that the usecase is as follows: user wants to add/ remove another category (e.g. as in the provided link Echarging data). After adding the category (s)he can select from a list of categories to add one of them. Thanks for letting me know.

**Comment by pkritzinger** [comment]
@RudiThoeni @gappc just wanted to shortly ask if you could provide feedback on this? 
thanks in advance.

**Comment by RudiThoeni** [comment]
@pkritzinger we continued the discussion into this PR https://github.com/noi-techpark/it.bz.opendatahub.databrowser/pull/555

**Comment by sseppi** [comment]
As agreed in during the sprint meeting, the preferred solution is the following:

https://5.databrowser.gappc.net/dataset/edit/tourism/v1/ODHActivityPoi/echarging_it*220*ebz000043#additional-properties

Wit the following considerations:
- to add a new property in the "Additional Properties" home it should be addedd a dropdown with an add button.
- in the "Additional Properties" home give the possibility to remove a property (**Warning**: we need to notify that by removing )

**Comment by sseppi** [comment]
@RudiThoeni This issue is solved with the implementation of the Additional Properties. right?

**Comment by RudiThoeni** [comment]
yes we can close it
