### ISSUE TITLE
As a Data Editor I want the possibility to add optional "Additional Properties" to a dataset (e.g. the eCharging accessability for the POI eCharging stations), to add  specific information only with needed.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#573]
In this iteration has been decided to:

- limit max one additional properties per dataset
- implement the v2 of the design

**Comment by sseppi** [comment]
Link to figma:
https://www.figma.com/design/DmuP6Dbv5LzkCNOXrDnWIL/2023-2024?node-id=2447-7398

**Comment by gappc** [comment]
@sseppi seems to work (see e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/detail/tourism/v1/ODHActivityPoi/echarging_leitner%20energy:csu%20soc.%20coop.%20-%20parkdeck%20-%2011kw%20-%20bozenbolzano%20-%20a.%20volta%20str.%2013via%20a.%20volta%2013:1#additional-properties), can we close this issue?
