### ISSUE TITLE
As a Data Browser user I want a compacter table view, to have a better focus on data and key functionalities

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#575]
During the sprint meetings and the testing, it emerged that there is the need to review the design of:

- the components in the header of the Table View (e.g. search item, language switcher, ...) to allign them and clean up the header;
- improve and compact the table view, to maximize the focus on the data shown.

The steps to implement this issue are:
- [x] @pkritzinger will propose a desing;
- [x] @MatteoBiasi will do ana analysis of the impact on the existing component and see if the changes can be applied also to the components integrated in other places in the data browser;
- [x] @pkritzinger will finalize the design based on the feedback emerged from the analysis;
- [x] @MatteoBiasi will implement the changes

**Comment by pkritzinger** [comment]
@sseppi @MatteoBiasi this is the first draft of the optimized design.
https://www.figma.com/design/DmuP6Dbv5LzkCNOXrDnWIL/2023-2024?node-id=2646-5382&t=d5M8J8DHL80jfTxr-1

**Comment by gappc** [comment]
@sseppi the proposed design changes are implemented (see e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation), can we close this issue?

**Comment by sseppi** [comment]
@gappc Yes, we can close the issue.
