### ISSUE TITLE
BUG: toggle "No metadata available" and "Deprecated" in Dataset Overview works partially

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#576]
I tried to set the filters "No metadata available" and "Deprecated" in the Dataset Overview but it seems that the toggle isn't in sink with the text.

https://databrowser.opendatahub.testingmachine.eu/dataset-overview

If I click on the text "No metadata available" and "Deprecated" the filter is set but the Toggle doesn't update.

- **Device**: Desktop
- **Operating System:** Ubuntu 24.04
- **Browser:** Chrome (v 125.0.6422.141), Brave (1.67.119) and Firefox (127.0.1)
- **Problem Description:**
The steps to reproduce the problem are:
  1. Access the Dataset Overview: https://databrowser.opendatahub.testingmachine.eu/dataset-overview 
  As you can see from the screenshot below 146 Dataset are shown and the filters are all deactivated.
![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/28c98a6a-66c6-4a9c-bd6f-eadcc36194cb)
  3. Activate the filter deprecated by clicking on the text: as you can see in the screenshot below the filter is set (only 3 dataset are found) but the toggle isn't updated
![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/243556ec-73e7-43ee-b870-9f82d4e2cea9)
  5. Deactivate the filter by clicking on the toggle: as you can see in the screenshot below the filter is deactivated since all 146 Dataset are rendered but the toggle is active like the Deprecated filter is still set
 ![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/06620ae6-1511-4b95-8bc6-e1c2be12a7af)
  7. Activate the filter deprecated by clicking on the toggle: as you can see from the screenshot below, the filter is set since only 3 dataset are shown and the toggle is updated
 ![Image](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/7909989/1a56a744-0a59-48b3-83f9-b57e11e28b0d)

 - **Expected behaviour:**I would like that the toggle gets updated also if I activate the filter by clicking on the text and not only on the toggle.

**Comment by gappc** [comment]
@sseppi seems to work (see e.g. https://databrowser.opendatahub.testingmachine.eu/), can we close this issue?

**Comment by sseppi** [comment]
@gappc I agree, I close the issue.
