### ISSUE TITLE
Filtering bug when page number is not 1

### ISSUE THREAD

**Issue by d3liaa** [noi-techpark/it.bz.opendatahub.databrowser#583]
I noticed a descrapency when filtering the table view.

first case: you are in the page 1 and then filter. It works and gives you the result
![Screenshot 2024-07-03 162704](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/101118017/af343ea1-0fd4-4e5f-b836-431a3c539e51)

second case: You are viewing any other page of the table view and then filter or do a basic search. The filter says there are no results available
![Screenshot 2024-07-03 162724](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/assets/101118017/3d85fad3-9dde-4dbd-9dc5-0d51c7ca4988)

**Comment by gappc** [comment]
@RudiThoeni yes, that seems to be a bug :+1: 

In my opinion, when search or filters change, the first result page should be shown. That would avoid the problem you mentioned and it should be less confusing for the user.

Example: as of now, if I'm on page 2 and apply a search, I stay on page 2 without indication that there are other results `before` the current page. Who would think of that? ;)

Instead, if we return on the first page after search / filters change, then the first results are presented to the user.

If implemented the new behaviour in PR #594, you can take a look at it here: [https://3.databrowser.gappc.net/dataset/table/tourism/v1/EventShort?source=noi](https://3.databrowser.gappc.net/dataset/table/tourism/v1/EventShort?source=noi)

**Comment by sseppi** [comment]
> @RudiThoeni yes, that seems to be a bug 👍
> 
> In my opinion, when search or filters change, the first result page should be shown. That would avoid the problem you mentioned and it should be less confusing for the user.
> 
> Example: as of now, if I'm on page 2 and apply a search, I stay on page 2 without indication that there are other results `before` the current page. Who would think of that? ;)
> 
> Instead, if we return on the first page after search / filters change, then the first results are presented to the user.
> 
> If implemented the new behaviour in PR #594, you can take a look at it here: https://3.databrowser.gappc.net/dataset/table/tourism/v1/EventShort?source=noi

@gappc I fully agree! Also other systems does the same and users are used to this behaviour.
I think we can merge the PR #594 and then test it.

**Comment by gappc** [comment]
@sseppi seems to work (see e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/EventShort), can we close this issue?
