### ISSUE TITLE
BUG: missing save button on mobile

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#589]
- **Device**: e.g. Mobile - Google Pixel 4a
- **Operating System:** Android 13
- **Browser:** Firefox 129.0
- **Problem Description:**
If I add/change something in one record the Save Button doesn't appear. The only way to save is try to exit from the record and than appeas the usaved data warning (see screenshot below).
![Screenshot_20240812-153043](https://github.com/user-attachments/assets/c063a5ff-17c8-4b00-ac63-1171f4994717)

_Steps replicate the problem_

  1. Access the Data Browser (testing environment: https://databrowser.opendatahub.testingmachine.eu/) on mobile
  2. Make the Login
  3. Access the "eCharging Station Accessibility" dataset: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/ODHActivityPoi?tagfilter=electric+charging+stations
  4. Access the Edit Mode of one Station randomly: https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/ODHActivityPoi/echarging_it*220*ebz000043
  5. Change randomly a data

- **Expected behaviour:**
Once the user changes something save and cancel button should appear, to save or undo the changes.
See as example the red (red color only to remark my proposals) buttons I added to the screenshot below.
![Screenshot_20240812-144037 (seconda copia)](https://github.com/user-attachments/assets/d69ffb6f-4495-4aae-b0fd-b92ee268fbe6)
@mmalfertheiner @pkritzinger : what do you think about my proposal.

**Comment by pkritzinger** [comment]
@sseppi agree. The screenshot below shows the expected behavior in the design.

![image](https://github.com/user-attachments/assets/8f7d5511-4ee1-47b4-97dc-b6a8085f45bf)

**Comment by gappc** [comment]
@sseppi @pkritzinger the buttons were visible at the bottom of the screen, after scrolling down. PR #592 fixes that issue, it should works as expected after the merge.

**Comment by gappc** [comment]
@sseppi the PR was merged, should we close this ticket?

**Comment by gappc** [comment]
@sseppi the PR #592 did not resolve the problem 100%, I need to take another look at it

**Comment by gappc** [comment]
@sseppi please take a look at it e.g. https://9.databrowser.gappc.net/dataset/edit/tourism/v1/Accommodation/5E4BEFD440200CE4732A7FA30897C402

It should work now

**Comment by sseppi** [comment]
> @sseppi please take a look at it e.g. https://9.databrowser.gappc.net/dataset/edit/tourism/v1/Accommodation/5E4BEFD440200CE4732A7FA30897C402
> 
> It should work now

@gappc now it seems to work properly, I will accept the PR you did and test it again in the testing environment.

**Comment by gappc** [comment]
@sseppi seems to work (see e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/edit/tourism/v1/Accommodation/5E4BEFD440200CE4732A7FA30897C402#contact), can we close this issue?

**Comment by sseppi** [comment]
@gappc I tested on my mobile phone and everything seems to work fine now.
I close the issue.
