### ISSUE TITLE
Improve the behavior and default value stored in the JSON of a toggle element

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#597]
Thanks to the feedback of a user, we noticed that the default value of all toggle elements seems to be misleading. Once the user creates a new record all toggle are set to false per default but in the JSON is stored null value. To store a false value the user has to click twice on the toggle to activate it and de-activate it. This seems to be not user friendly, since the user sees the toggle set on false per default.

### Steps to replicate the issue
1. Login into the Data Browser
2. Open the table view of a Dataset (e.g. Articles by NOI: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Article?source=noi)
3. Click on add a record
4. Open the JSON DIFF (you can see a completely empty JSON)
![Image](https://github.com/user-attachments/assets/ceb9cc9d-708b-4fc3-a617-b97e3d33ff77)
5. Click on a toggle (e.g Active on Source) and in the JSON DIFF appers a value ```"Active": true```
![Image](https://github.com/user-attachments/assets/9948dece-0dac-43b3-867b-aead5e50326f)
6.  Click again on the same toggle and in the JSON DIFF appers a value ```"Active": false```
![Image](https://github.com/user-attachments/assets/ab54016b-7718-4279-b6b7-918e2259b70f) 

### User expectation
The user, since sees the toggle inactive (red) per default expects that the value is stored false per default.

### Possible solutions
- Add a third state for the toggle allowing the user to choose between ```true```, ```false``` and ```inactive/null```
- Set per default all toggles to false and also store in the JSON the value ```false``` per default

**Comment by pkritzinger** [comment]
@sseppi @gappc honestly, I lack technological know-how here. What does a "null"-value mean in detail? Is it something like "not defined"?

**Comment by sseppi** [comment]
> @sseppi @gappc honestly, I lack technological know-how here. What does a "null"-value mean in detail? Is it something like "not defined"?

@pkritzinger yes, a null value means that the field is empty. In this case specifically it hasn't any status (neither true or false) assigned.

**Comment by pkritzinger** [comment]
@sseppi ok, but then we should set null as default and provide a dropdown to to the user to select between the different options (null, false, true)

fyi @gappc

**Comment by sseppi** [comment]
During the Refinement Meeting it has been decided, to keep the 3 levels and use "null" as default value.

@pkritzinger will now think a possible graphical solution to manage the 3 values (true, false and null)

**Comment by pkritzinger** [comment]
@sseppi @gappc what do you think of this solution?

![image](https://github.com/user-attachments/assets/6b8da840-1734-4309-aa01-009da67eaa95)

**Comment by gappc** [comment]
I like :)

**Comment by sseppi** [comment]
@pkritzinger I like it too. 

Since null is a technical term that is dissicult to understand for non technical users, I would propose only a change of name and to keep also the color status as follows:

- Not Assigned (switcher color: gray)
- True (switcher color: green)
- False (switcher color: red)

What do you think? If you agree, I think we are ready to implement this feature.

**Comment by pkritzinger** [comment]
@sseppi you mean like this?
![image](https://github.com/user-attachments/assets/501b6f07-94a5-4019-b670-fdfaec564735)

Honestly, not sure if this does not get too colorful. Would stick to the original (green suggestion.).

**Comment by sseppi** [comment]
@pkritzinger I meant to color the whole switcher, also the border, like we do with the actual switcher (see screenshot below).

![Screenshot from 2024-09-17 15-45-21](https://github.com/user-attachments/assets/61a024bb-b65d-4b22-8f7d-9f475652a86e)

But I let you decide, which is the best solution to be applied.

**Comment by pkritzinger** [comment]
@sseppi like this?
![image](https://github.com/user-attachments/assets/2e96b751-e3d1-49f2-ab00-1c65f9346f84)

Not sure if that works, we would have a constant change of font colors as well. I'm afraid that looks weird.

**Comment by sseppi** [comment]
> @sseppi like this? ![image](https://private-user-images.githubusercontent.com/92454516/368228275-2e96b751-e3d1-49f2-ab00-1c65f9346f84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODY3ODYsIm5iZiI6MTcyNjU4NjQ4NiwicGF0aCI6Ii85MjQ1NDUxNi8zNjgyMjgyNzUtMmU5NmI3NTEtZTNkMS00OWYyLWFiMDAtMWM2NWY5MzQ2Zjg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE1MjEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYWVmMjY4NGMxNGJjNzI5MmNiNGExNTY4ZTc0NzU4NmNjYzZlODdlMWE3YTZhNDBhMDIxYWEzODQyZTJhMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4MvAOoaj-BmkkNxRRqW0mnQJQ2rCR1hGjxFIqO8s2r0)
> 
> Not sure if that works, we would have a constant change of font colors as well. I'm afraid that looks weird when interacting with the toggle. I would honestly stick to the previous solution.

@pkritzinger fine for me.

**Comment by pkritzinger** [comment]
@sseppi find the link to the design here:
https://www.figma.com/design/DmuP6Dbv5LzkCNOXrDnWIL/2023-2024?node-id=3400-2726&t=Aqc1LTBFLNznyqoc-1

**Comment by sseppi** [comment]
@pkritzinger during the meeting we decided to use undefined instead of null

**Comment by pkritzinger** [comment]
@sseppi wording has been updated, see link to design below:
![Image](https://github.com/user-attachments/assets/edd2513c-9b45-44c5-8ac4-f9a48dffc968)

https://www.figma.com/design/DmuP6Dbv5LzkCNOXrDnWIL/2023-2024?node-id=3400-2726&t=0puXalq3WZ4uGn3o-1

**Comment by gappc** [comment]
@RudiThoeni when this 3-state toggle is set to "Undefined", should the value that gets written, be `undefined` or `null`?

**Comment by gappc** [comment]
@sseppi, @mrabans @pkritzinger, @Mazzolintis, @RudiThoeni here you can try out the first implementation: https://1.databrowser.gappc.net/dataset/edit/tourism/v1/Article/BCCEEEC0-739A-90F3-F0E8-268816DBAD48 (see first image below)

![image](https://github.com/user-attachments/assets/f973dc77-9f22-4c38-9246-70d7b2476b6e)

Things to note:

- at the moment, the component is used just in that one place shown in the screenshot
- for new records (e.g. https://1.databrowser.gappc.net/dataset/new/tourism/v1/Article), no value is selected, because there is no value yet (see image below). The component emits a new value to the underlying system only when something is selected. In essence, writing no value for a property should be the same as setting the property value to `undefined` (@RudiThoeni is this correct?). The difference to the current `Toggle` component is:
  - the user sees that nothing is selected (the `Toggle` component shows wrongly a value of `false` if nothing is selected)
  - the user can set the value to `undefined` / `null` intentionally

![image](https://github.com/user-attachments/assets/8bdd09e9-a9ee-4220-aa4d-4a831440f010)

Please take a look and let me know what you think.

**Comment by sseppi** [comment]
@gappc Thank you for the fast implemantation

In my point of view the "undefined" status of the toggle corresponds to the "Null" value in the database. For that reason I would propose to write "Null" in case the user selects "undefined" and use that status as default status.

@RudiThoeni do you agree?

**Comment by RudiThoeni** [comment]
@gappc @sseppi  yes let's write `null`

**Comment by RudiThoeni** [comment]
PR merged issue closed

**Comment by sseppi** [comment]
I tested the component and everything seems to work fine.
Close the issue.
