### ISSUE TITLE
BUG: "add a record" button disappearing in new Data browser version 

### ISSUE THREAD

**Issue by lukmay** [noi-techpark/it.bz.opendatahub.databrowser#604]
**Operating System**: Windows11
**Browser**: Edge
**Problem Description**:
In the latest test version of the data browser, I've noticed that the 'Add a record' button is no longer visible in the table view when the screen width reaches 767 pixels or below. This issue does not occur in the currently available testing or production versions of the software.

How it looks like in the working versions:

https://github.com/user-attachments/assets/49cd15fc-fb13-4777-9a03-80a386ddbc2f

How it looks like in the very newest version:

https://github.com/user-attachments/assets/82ecaeed-6577-4502-8c90-ed701a69c18d

**Comment by gappc** [comment]
@sseppi seems to be fixed (see. e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation), can we close this issue?

**Comment by lukmay** [comment]
@gappc @sseppi I was also testing it. 
Now it works as expected!

**Comment by sseppi** [comment]
@lukmay @gappc thank you for testing! I reached the same results too.
I close the issue.
