### ISSUE TITLE
Search box in the Detail Views doesn't work

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#609]
To replicate the issue:

- access the detail view of a record of a dataset
- type something in the search box
- click on search
- nothing happens

Possible expected behaviour

1. the search is shown only in the table view and not in the detail/edit/raw view
2. the search box is shown also in the table view and not in the detail/edit/raw view and if the user searches something is redirected to the table view of the datataset showing the result of the search he did

**Comment by sseppi** [comment]
@pkritzinger @Mazzolintis which way would you suggest?

Solution 1. is probably simpler to implement, but solution 2. is probably more user friendly since it reduces the number of clicks to do a new record search within a dataset.

**Comment by pkritzinger** [comment]
@sseppi I don't see the updated version with the search in the Header yet. 
I'm using this domain: databrowser.opendatahub.testingmachine.eu

Anything I need to do/ change?

**Comment by gappc** [comment]
@pkritzinger an up-to-date deployment of PR #596 can be found here: https://0.databrowser.gappc.net/

**Comment by sseppi** [comment]
@pkritzinger for now the new version is still in the staging environment on the Gapp's servers. You can reach it at the following link: https://0.databrowser.gappc.net/

**Comment by sseppi** [comment]
> @gappc thanks for sharing the link!
> 
> @sseppi
> 
> > the search box is shown also in the table view and not in the detail/edit/raw view and if the user searches something is redirected to the table view of the datataset showing the result of the search he did
> 
> Not sure if I got your msg. correctly? You mean the search is also shown in the detail/edit/raw view? If yes: I wouldn't do that but rather go with option 1. As a user I would always expect to be able to search the respective page if it was visible there, i.e. if I see the search in the detail view, I expect to search the data of the detail view and not of another (at that moment) non-visible section.

@pkritzinger Thank you for the reply. I would go for option 1 too, which is also the easiest to implement.

**Comment by gappc** [comment]
@sseppi should be fixed (see e.g. [https://databrowser.opendatahub.testingmachine.eu/dataset/detail/tourism/v1/Article/BCCEEEC0-739A-90F3-F0E8-268816DBAD48](https://databrowser.opendatahub.testingmachine.eu/dataset/detail/tourism/v1/Article/BCCEEEC0-739A-90F3-F0E8-268816DBAD48)). Can we close this issue?

**Comment by sseppi** [comment]
@gappc Yes, this has been fixed. I close the issue.
