### ISSUE TITLE
Warnings in the console in Detail view

### ISSUE THREAD

**Issue by gappc** [noi-techpark/it.bz.opendatahub.databrowser#614]
There are warnings in the console when opening the detail view of a record (see image below), e.g. BASE_URL/dataset/detail/tourism/v1/Accommodation/5E4BEFD440200CE4732A7FA30897C402

The warnings appear only in development mode.

It seems that the problem is related to PR #596, see also comment [https://github.com/noi-techpark/it.bz.opendatahub.databrowser/pull/596#issuecomment-2381437866](https://github.com/noi-techpark/it.bz.opendatahub.databrowser/pull/596#issuecomment-2381437866)

![image](https://github.com/user-attachments/assets/d461f1c6-7e24-418f-bdf5-42ab97e66657)

@a-crea could you please take a look? Maybe there is room in PR #612 for this fix, too.

**Comment by a-crea** [comment]
They are already fixed in #612 :)

**Comment by gappc** [comment]
Ah, didn't notice that one, thx 😊
