### ISSUE TITLE
A component for the number input is missing

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#628]
As a data editor I want a component to input numbers, to open the number keyboard per default on mobile.

In the actual Data Browser development we have only the ```CellComponent.StringCell``` component, which allows the input of Strings. But we can't limit the user to input only numbers (int or doubles).

Maybe it could be useful to extend the component or create a new component to have the possibility to limit the input functionality only to numbers (int or double). This extension would:

- help the user in the input from mobile by opening the numbers keyboard;
- reduce the risk that the user inputs a string instead of a number;
- limit the user to input only ```int```, if ```int``` number are set;
- limit the risk to input the wrong comma separetor in case od ```double``` numbers.

**Comment by RudiThoeni** [comment]
It is already handled on Backend side see this Issue here
https://github.com/noi-techpark/odh-api-core/issues/453

**Comment by RudiThoeni** [comment]
At the moment double values have to be passed as string with the dot "10.5"
example object that is created
```
"CarParkingSpaceNextToEachOther": {
"Flat": null,
"Width": 150,
"Length": null,
"Gradient": 14.8,
"Pavement": null,
"LateralInclination": 12,
"ManeuvringSpaceSignagePresent": null
},
```

**Comment by gappc** [comment]
@sseppi @RudiThoeni PR #636 adds support for number inputs to `InputCustom` and `StringCell` components.

Example usage of StringCell in config:

```json
{
  title: 'Age',
  component: CellComponent.StringCell,
  objectMapping: { text: 'Age' },
  params: { type: 'number' }
}
```

In essence, you can set the `type` in the `params` property of the `StringCell`. That type will be promoted 1:1 to the underlying `input` HTML element. Take a look at the MDN article on input types for more in formation: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types)

**Comment by RudiThoeni** [comment]
@gappc thx i tested everything works , PR merged, @sseppi i added the input type number to the echargingstations please test

**Comment by sseppi** [comment]
The new component is online in Prod. I close the issue.
