### ISSUE TITLE
BUG: link in tooltip doesn't work

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#663]
If I click on a button included in a tool-tip doesn't work, since there isn't any reaction if I click on it.

**To reproduce the problem:**

1. open a table view in the testing data browser: https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation
2. open the filter side bar
3. click on the info icon near "ALL FILTERS"
![Image](https://github.com/user-attachments/assets/9d6b546c-e580-4f4f-bb10-d637d5baebe1)
4. click on the "Open wiki" button
![Image](https://github.com/user-attachments/assets/6a809933-78f0-4426-a2d6-d9e693174501)

**Expected behaviour**
The right wiki page must be opened in a new window.

**Comment by gappc** [comment]
@sseppi PR #668 fixes this issue

**Comment by RudiThoeni** [comment]
works can be closed

**Comment by sseppi** [comment]
@Xeroxi91 the bug has been solved, now everything should work fine in the testing environment.

https://databrowser.opendatahub.testingmachine.eu/
