### ISSUE TITLE
EPIC: 1st version of the Edit View Implementation

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#68]
As a Open Data Hub content manager I want an edit view in order to be able to see, manage, change and delete my data.

**Comment by sseppi** [comment]
I add in this comment some feedback about the edit view provided by @gappc :

- discuss authorization requirements and enforcements (roles, how / what to show and allow / deny)
- discuss how edit / update works in ODH API, are there some surprises or things to know, is it always one single POST / PUT / DELETE or are some changes more complex? => ask Rudi
- discuss edit UI / UX
- discuss validation
- discuss visibility of navigation points / links / buttons
- Edit data load view (similar discussion as in "Table data load view")

**Comment by sseppi** [comment]
@pkritzinger as far as I know, Customer Care configured all Edit Views. Can you please review it and let us know if everything is inline with your proposals?

@gappc from a technical point of view all functionalities should have been implemented, or do I'm wrong?

**Comment by gappc** [comment]
@sseppi the points mentioned in this issue are resolved, but I can not say 100% if all points regarding the EditView are done. Is there some place where we can look that up?
