### ISSUE TITLE
Markdown for Table/Detail/Raw View

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#71]
The Table / Detail / Raw View header show information about a dataset. In the first MVP, we support only text for these texts.

This issue has been open, in order to understand if we should support a markup language (e.g. Markdown, HTML) in order to be able to add formatting / links to the header texts.

**Comment by gappc** [comment]
@sseppi yes, let's do that.

**Comment by sseppi** [comment]
@mrabans I think this issue has been solved by implementing the MetaData API. Do you agree?

**Comment by mrabans** [comment]
@sseppi exactly, this can be closed as it is already solved with the Metadata API

**Comment by sseppi** [comment]
@mrabans super thank you!
