### ISSUE TITLE
Table View - Sorting

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#75]
ODH seems to support "rawsort", at least for some endpoints (see https://github.com/noi-techpark/odh-docs/wiki/Using-rawfilter-and-rawsort-on-the-Tourism-Api#rawsort) => talk to Rudi
- is it feasible to use it for sort, e.g. because of performance considerations?
- is rawsort applicable onto each data property / column?
- are there other things to take into consideration for sort?

**Comment by sseppi** [comment]
I will keep this issue open, since also this is a feature we will need to implement at the beginning of 2023.

@gappc in the meantime I think that Rudi shared with you per email all information you need about raw sorting. Right?

**Comment by sseppi** [comment]
OK, as soon as we start with the planning of this activity (end of 2022 or begin 2023) we will have a dedicated meeting with @RudiThoeni to clarify edge cases.

In any case I would start with the simple standard cases and then implement the complex/edge one in a second step.

**Comment by sseppi** [comment]
@pkritzinger and @Mazzolintis I post here below two screenshot example on how we have to implement the sorting in the first raw of the Table View.

**Google Sheet**
By clicking on the icon on the right side of the first raw it opens the sorting/filter tooltip
![Schermata da 2023-03-22 11-29-00](https://user-images.githubusercontent.com/7909989/226880147-2a01a537-5c8b-4a5f-92bb-aac16aa7009b.png)

**CRM Dynamics**
By clicking on the icon on the right side of the first raw it opens the sorting/filter tooltip
![Schermata da 2023-03-22 11-15-07](https://user-images.githubusercontent.com/7909989/226880945-2aff8aba-fca1-4936-bf43-92fcd8372e79.png)

If the sorting is active on a column a small arrow (up or down accordingly to the chosen sorting) appears on the right side of the column name.
![Schermata da 2023-03-22 11-54-35](https://user-images.githubusercontent.com/7909989/226882414-64186f0f-4244-456f-8d20-9f8904164ce7.png)



I hope this information helps you in your work.

**Comment by sseppi** [comment]
I put here below the link to the first version of the sorting design implemented by Studio Hug:
https://www.figma.com/file/O4voW1HWCjB1rDibiZtWEI/MVP3?node-id=523-4831

**Comment by sseppi** [comment]
Hi all,
I took a little bit of time to make some testing using the `rawsort` functionality of the APIS (see documentation below):
https://github.com/noi-techpark/odh-docs/wiki/Using-rawfilter-and-rawsort-on-the-Tourism-Api#rawsort

In my point of view, in the first iteration, we can use it for all columns and the behaviour isn't that bad. Just look a the results of the test that I share below:

- for the images, as far I understood, the rawsort orders by default the items in base of the number of images there are in the `ImageGallery` field. If so, if the user orders the Image column the result would be that either he sees the records without images before or he sees all records with images before. See the link below for the example: 
https://github.com/noi-techpark/odh-docs/wiki/Using-rawfilter-and-rawsort-on-the-Tourism-Api#rawsort
- for the Location if we use the `LocationInfo` field, it seems that the sorting is done by sorting the Reagions in alphabetical order
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation?rawsort=-LocationInfo
- for the single value column (e.g. Title, Accomodation Type, etc.) I would suggest sort accordingly to the parameter that is shown.

In case that more fields are added to the `rawsort` the sorting is done considering the order of the fields passed:
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation?rawsort=Shortname,-LocationInfo
https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation?rawsort=-LocationInfo,Shortname
For this reason I think that is important to decide if we allow a multi column sorting:
- if yes, we have to clearly notify the user that the result of the sorting can change if he selects the column to be ordered in a different order;
- if not, we have to decide what to do if the user sorts the column A and the tries to sort the column B.

I hope that this comment helps you to prepare the next meeting.

**Comment by sseppi** [comment]
Decision taken during the today's meeting:

- the sorting will include the possibility to sort only one single column per time;
- the sorting will be done using the main filed shown in the column;
- the sorting will be implemented also in the "Generated View".

We need to identify a graphical solution to reset the sorting to the default from a user interface point of view.

**Comment by gappc** [comment]
Please take a look at the first implementation of Table View sorting, introduced with #be3f7fb87285ef09659a03f66a95e11b91fd5e72, e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Article?rawsort=Detail.en.Title

Sorting works by clicking on the table header and has 3 states that get cycled through on each click: not sorted, sorted ascending, sorted descending

Things to consider:

- the sort icon appears only on sort, a simple arrow is used (need to discuss this visualization)
- sorting sometimes gives strange results, e.g. when sorting on the `Title` field. The reason for this is, that the data for a column may be `null`, the empty string (= no characters) or something meaningful. The backend sorts `null` and the empty string differently, this may not be obvious to the user. We should discuss if this is a problem and decide what to do
- sorting by arrays / objects is not always intuitive, but I think we know that already

Please take a look at the solution, play a bit around with it and provide some feedback

**Comment by sseppi** [comment]
@gappc Thank you for the implementation! It looks very promising and now I'm curious to see the design provided by @pkritzinger and @Mazzolintis .

I share below what we discussed during the meeting and the feddback I collected from Rudi.
> Things to consider:
> 
>     * the sort icon appears only on sort, a simple arrow is used (need to discuss this visualization)
>
Paul and Matthias are working on a first design proposal. They will share it as soon as possible.
> 
>     * sorting sometimes gives strange results, e.g. when sorting on the `Title` field. The reason for this is, that the data for a column may be `null`, the empty string (= no characters) or something meaningful. The backend sorts `null` and the empty string differently, this may not be obvious to the user. We should discuss if this is a problem and decide what to do
>
This issue will be resolved on the backend side, so no changes on the frontend are needed for now. 
>
>     * sorting by arrays / objects is not always intuitive, but I think we know that already
>
Sorting of arrays/objects/lists is done by number of items returned. Since the behaviour is always the same and is easily explicable to the final user, we decided to keep it like it is in this iteration. 
In case of need, improvements will be planned in next iteration and based on the feedbacks from the real users.

**Comment by sseppi** [comment]
The design of the sorting is available at the following link:
https://www.figma.com/file/DmuP6Dbv5LzkCNOXrDnWIL/2023?node-id=207-2158

@gappc will implement it like proposed.

**Comment by pkritzinger** [comment]
@gappc Iconcina non è dinamica a base dell'impostazione dell'utente.

**Comment by gappc** [comment]
@pkritzinger @sseppi fixed as of 2b5e1024fc16d191de1976cbc719174ec3e11dc5, see e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Accommodation

If ok, please close the issue.
