### ISSUE TITLE
Table View - Empty table visualization

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#78]
Empty table visualization, e.g. if filter settings lead to zero results (Studio Hug proposal: https://app.zeplin.io/project/619297bb195e0113987fbd5c/dashboard?sid=61929830770bc21914081664) => if we implement it as proposed, there is no way to e.g. reset / modify filters, because there is no table visible at all

**Comment by sseppi** [comment]
@gappc this issue comes from a feedback that you did during the implementation of the MVP2. Did we solved the problem in the meantime?

**Comment by gappc** [comment]
@sseppi if a request in the Table View returns zero results, an empty table will be shown (see, e.g. https://databrowser.opendatahub.testingmachine.eu/dataset/table/tourism/v1/Article?idlist=1). It would be good to indicate to the user that no results were found and to give a hint on what to do next. Maybe we could discuss this with studiohug?

**Comment by sseppi** [comment]
OK, I'll suggest to talk with @pkritzinger about how to help the user in understanding that no result has been found and introduce this one of the next iterations.

**Comment by gappc** [comment]
@sseppi: can this issue be closed? I saw there is a follow-up issue to improve the message: https://github.com/noi-techpark/it.bz.opendatahub.databrowser/issues/285
