### ISSUE TITLE
NoConfig View: Show data provided by the Open Data Hub endpoints by using only default components

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#90]
In the first iteration of this functionality the following components should be included.

- [x] The data should be listed by using default visualization components for the following data types:
  - [x] String
  - [x] Numbers
  - [x] Boolean
  - [ ] GPS coordinates (Point on a map) --> Optional
  - [ ] Image list (Image Gallery) --> Optional
- [ ]

**Comment by gappc** [comment]
Note: optional parts of this issue were not implemented.

**Comment by sseppi** [comment]
I added a new issue (#188 ) for the optional components and I close this issue
