### ISSUE TITLE
NoConfig View: Detail view automatically generated from API schemas shown in swagger

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#92]
Functionality to be included in the first iteration
- [x] Field order
  - [x] Show attributes in order as they appear in the JSON
  - [x] If there is an attribute called "Id" show it as first field
  - [x] If there is an attribute called "Name" or "Title", show it as second field
  - [x] If an attribute has an "unknown type", go iteratively to the next level until finding one of the known types (string, number, boolean)

**Note:** For MVP2 the detail view will have 1 column only, knowing that the hierarchical view of sub-attributes can/might invoke a horizontal scrolling

**Comment by gappc** [comment]
The tree traversal rendering is not implemented at the moment. A new issue was added, see #101.

@sseppi : is the tree traversal rendering part of MVP2? The text in this issue is not 100% clear.
